<form action="/admin/create-tutoring-invoice" method="post" class="form-horizontal">
    <div class="form-group">
        <p class="col-sm-offset-2 col-sm-6"><?php if (isset($flash['message'])) {echo $flash['message'];} ?></p>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Email</label>
        <div class="col-sm-6">
            <input name="email" type="text" autofocus="autofocus" class="form-control" placeholder="Email" value="">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Addressee</label>
        <div class="col-sm-6">
            <input name="addressee" type="text" class="form-control" placeholder="Ms. Jones" value="">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Tutoree</label>
        <div class="col-sm-6">
            <input name="tutoree" type="text" class="form-control" placeholder="Tommy" value="">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Start Date</label>
        <div class="col-sm-6">
            <input name="startDate" type="date" class="form-control" value="<?php echo $today->format('Y-m-d'); ?>">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Start Time</label>
        <div class="col-sm-6">
            <input name="startTime" type="time" class="form-control">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">End Date</label>
        <div class="col-sm-6">
            <input name="endDate" type="date" class="form-control" value="<?php echo $today->format('Y-m-d'); ?>">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">End Time</label>
        <div class="col-sm-6">
            <input name="endTime" type="time" class="form-control" value="<?php echo $today->format('H:i'); ?>">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Billable Hours</label>
        <div class="col-sm-6">
            <input name="hours" type="text" class="form-control" placeholder="2.50" value="">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Hourly Rate</label>
        <div class="col-sm-6">
            <input name="hourlyRate" type="text" class="form-control" placeholder="100" value="">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Notes</label>
        <div class="col-sm-6">
            <textarea name="notes" rows="10" class="form-control"></textarea>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" name="submit" class="btn btn-default">CREATE INVOICE</button>
        </div>
    </div>
</form>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
