<div class="row">
	<div class="col-sm-6 col-sm-offset-2">
		<?php if (isset($flash['message'])) {echo $flash['message'];} elseif 
			(isset($flash['firstNameError']) || isset($flash['lastNameError']) || isset($flash['emailError'])) { ?>
				<span class="text-danger">Your MCAT<sup>&reg;</sup> class registration was not processed. Please check the error messages below and try again.</span>
			<?php } else { ?>
				<p class="text-primary">Thank you for registering for a Lenox Hill Premedical MCAT<sup>&reg;</sup> class! Please verify the information below and fill in any missing fields.</p>
		<? } ?>
		<ul class="list-group">
			<li class="list-group-item"><strong>CLASS: </strong><?php echo $class['Topic']; ?></li>
			<li class="list-group-item"><strong>INSTRUCTOR: </strong><?php echo $class['Instructor']; ?></li>
			<li class="list-group-item"><strong>DATE: </strong><?php echo $class['Start']->format('l F jS\, Y') ?></li>
			<li class="list-group-item"><strong>TIME: </strong><?php echo $class['Start']->format('g:i A').' - '.$class['End']->format('g:i A'); ?></li>
			<li class="list-group-item"><strong>LOCATION: </strong><?php echo $class['Location']; ?></li>
			<li class="list-group-item"><strong>PRICE: </strong><?php echo ($class['Price'] == 0) ? 'FREE' : '$'.$class['Price'].'.00'; ?></li>
		</ul>
	</div>
</div>
<?php if ($class['Price'] != 0) { ?>
	<form action="/class-registration?classId=<?php echo $class['ClassId'];?>" method="post" name="stripepurchaseclass" id="stripepurchaseclass" class="form-horizontal">
		<input type="hidden" name="classId" value="<?php echo $class['ClassId']; ?>">
		<div class="form-group">
			<label class="col-sm-2 control-label" for="firstname">First Name</label>
			<div class="col-sm-6">
				<input name="firstname" type="text" class="form-control" value="<?php 
					if (isset($flash['firstName'])) {
						echo $flash['firstName'];
					} elseif ($user) {
						echo $user['first_name'];
					}
				?>">
				<?php if (isset($flash['firstNameError'])) {
					echo '<ul class="text-danger"><li>' . $flash['firstNameError'] . '</li></ul>';
				} ?>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label" for="lastname">Last Name</label>
			<div class="col-sm-6">
				<input name="lastname" type="text" class="form-control" value="<?php 
					if (isset($flash['lastName'])) {
						echo $flash['lastName'];
					} elseif ($user) {
						echo $user['last_name'];
					}
				?>">
				<?php if (isset($flash['lastNameError'])) {
					echo '<ul class="text-danger"><li>' . $flash['lastNameError'] . '</li></ul>';
				} ?>
				<?php if (isset($flash['emailError'])) {
				echo '<ul class="text-danger"><li>' . $flash['emailError'] . '</li></ul>';
				} ?>
			</div>
		</div>
		<div class="col-sm-6 col-sm-offset-2"  style="text-align:center">
			<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
								data-name="Lenox Hill Premedical"
								data-image="public/images/apple-touch-icon-144x144.png"
								data-key="<?php echo $stripePublishableKey; ?>"
								data-amount="<?php echo ($class['Price'] * 100); ?>"
								data-description="<?php echo $class['Topic']; ?>"
								data-label="Reserve Seat"
								data-allowRememberMe="false">
			</script>
		</div><br/><br/>
		<div class="col-sm-6 col-sm-offset-2">
			Click to submit a one-time payment of $<?php echo $class['Price']; ?>.00. In the email field, please write the email address of the <i>student</i> who will be attending the class.
		</div>
		<h6 class="text-muted col-sm-6 col-sm-offset-2">
			NOTE: All payments to Lenox Hill Premedical are made on a one-time basis via a secure, licensed, third-party payment gateway (Stripe<sup>&trade;</sup> Inc.). Your payment information is SSL-encrypted and never stored on any server. Your information is secure!
		</h6>		
	</form>
<?php } else { ?>
	<form action="/class-registration?classId=<?php echo $class['ClassId'];?>" method="post" class="form-horizontal">
		<input type="hidden" name="classId" value="<?php echo $class['ClassId']; ?>">
		<div class="form-group">
			<label class="col-sm-2 control-label" for="firstname">First Name</label>
			<div class="col-sm-6">
				<input name="firstname" type="text" class="form-control" value="<?php 
					if (isset($flash['firstName'])) {
						echo $flash['firstName'];
					} elseif ($user) {
						echo $user['first_name'];
					}
				?>">
				<?php if (isset($flash['firstNameError'])) {
					echo '<ul class="text-danger"><li>' . $flash['firstNameError'] . '</li></ul>';
				} ?>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label" for="lastname">Last Name</label>
			<div class="col-sm-6">
				<input name="lastname" type="text" class="form-control" value="<?php 
					if (isset($flash['lastName'])) {
						echo $flash['lastName'];
					} elseif ($user) {
						echo $user['last_name'];
					}
				?>">
				<?php if (isset($flash['lastNameError'])) {
					echo '<ul class="text-danger"><li>' . $flash['lastNameError'] . '</li></ul>';
				} ?>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label" for="email">Email</label>
			<div class="col-sm-6">
				<input name="email" type="text" class="form-control" value="<?php
					if (isset($flash['email'])) {
						echo $flash['email'];
					} elseif ($user) {
						echo $user['email'];
					}
				?>">
				<?php if (isset($flash['emailError'])) {
					echo '<ul class="text-danger"><li>' . $flash['emailError'] . '</li></ul>';
				} ?>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-6" style="text-align:center">
				<button type="submit" name="submit" class="btn btn-success" value="">RESERVE SEAT</button>
			</div>
		</div>
	</form>
<?php } ?>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>