<?php $bucket = '/public/images/'; ?>
<div id="header"><table id="header_table"><tbody><tr><td>
                <div id="paginator">
                    <?php if (isset($paginationArray)) {
                        echo 'Questions ' . $paginationArray['min'] . '-' . $paginationArray['max'] . ' of ' . $paginationArray['total'];
                    } ?>
                </div>
            </td><td>
                <div id="logo_for_full_length_header">
                    <a style="color:white" href="/user"><i>LENOX HILL PREMEDICAL</i></a>
                </div>
            </td><td>
                <div id="timer"></div>
            </td></tr></tbody></table>
</div>
<div id="passage" onmouseup="processSelection(event);">
	<?php echo $passage; ?>
</div>
<div id="questions">
	<?php if ($currentSection == 'bio' || $currentSection == 'phys') {?>
		<button class="mcat_submit_button" style="width:160px; display:block; margin-left:auto; margin-right:auto" onclick="return getPeriodicTable('<?php echo $bucket; ?>periodic_table.png')">PERIODIC TABLE</button>
	<?php }?>
	<form id="mcatcontentpageform" action="/full-length/content-page/<?php echo $examId.'/'.$fullLengthNumber.'/'.$pageNumber; ?>" method="post">
	<?php foreach ($items as $item) { ?>
		<fieldset style="display:none"><legend><?php echo 'Item '.$item->offsetItemNumber; ?></legend>
			<div class="mcat_question_text"><?php echo $item->q; ?></div>
			<div class="label"><span class="mcat_answer_bubble_and_letter"><input type="radio" name="<?php echo $item->itemNumber; ?>" value="A<?php if (strpos($item->answer,'m') === 1 || strpos($item->answer,'m') === 0) {echo 'm';}?>" <?php if (strpos($item->answer,'A') === 0) {echo 'checked = "checked"'; }?> onclick="mcatCheck(this);">A) </span><div class="mcat_answer_choice_container"><span onclick="updateStrikeOut(this)"><?php echo $item->a; ?></span></div></div>
			<div class="label"><span class="mcat_answer_bubble_and_letter"><input type="radio" name="<?php echo $item->itemNumber; ?>" value="B<?php if (strpos($item->answer,'m') === 1 || strpos($item->answer,'m') === 0) {echo 'm';}?>" <?php if (strpos($item->answer,'B') === 0) {echo 'checked = "checked"'; }?> onclick="mcatCheck(this);">B) </span><div class="mcat_answer_choice_container"><span onclick="updateStrikeOut(this)"><?php echo $item->b; ?></span></div></div>
			<div class="label"><span class="mcat_answer_bubble_and_letter"><input type="radio" name="<?php echo $item->itemNumber; ?>" value="C<?php if (strpos($item->answer,'m') === 1 || strpos($item->answer,'m') === 0) {echo 'm';}?>" <?php if (strpos($item->answer,'C') === 0) {echo 'checked = "checked"'; }?> onclick="mcatCheck(this);">C) </span><div class="mcat_answer_choice_container"><span onclick="updateStrikeOut(this)"><?php echo $item->c; ?></span></div></div>
			<div class="label"><span class="mcat_answer_bubble_and_letter"><input type="radio" name="<?php echo $item->itemNumber; ?>" value="D<?php if (strpos($item->answer,'m') === 1 || strpos($item->answer,'m') === 0) {echo 'm';}?>" <?php if (strpos($item->answer,'D') === 0) {echo 'checked = "checked"'; }?> onclick="mcatCheck(this);">D) </span><div class="mcat_answer_choice_container"><span onclick="updateStrikeOut(this)"><?php echo $item->d; ?></span></div></div>
		</fieldset>
	<?php } ?>
</div>
<div id="footer">
    <table id="footer_table">
        <tbody>
        <tr>
            <td>
                <div id="footer_left">
                    <input id="previousButton" class="mcat_submit_button" type="submit" name="previous" value="PREVIOUS" onclick="return clickPreviousButton();">
                </div>
            </td>
            <td>
                <div id="footer_center">
                    <input class="mcat_submit_button" type="submit" name="review" value="REVIEW" onclick="clickReviewButton();">
                    <input class="mcat_submit_button" type="submit" name="mark" value="MARK" id="mark_button" onclick="clickMarkButton(); return false;">
                    <input type="hidden" name="timeRemaining" value="<?php echo $timeRemaining; ?>">
                    <input id="annotationCount" type="hidden" name="annotationCount" value="<?php echo $annotationCount; ?>">
                    <input id="annotationChanged" type="hidden" name="annotationChanged" value="FALSE">
                    <input id="annotation" type="hidden" name="annotation">
                </div>
            </td>
            <td>
                <div id="footer_right">
                    <input class="mcat_submit_button" type="submit" name="next" value="NEXT" onclick="return clickNextButton();">
                </div>
            </td>
        </tr>
        </tbody>
    </table></form>
	<img id="highlightButton" src="<?php echo $bucket; ?>highlight.png" style="position:fixed;zIndex:5;display:none"
 tabindex="0" hidefocus="hidefocus" draggable="false" ondragstart=" return false;" onblur="hideHighlightButton();">
</div>
<script type="text/javascript">
    if (document.forms[0].getAttribute('id') == 'mcatcontentpageform') {
        window.onload = initializeMcatChecks();
        window.onload = initializeExtraFields();
		window.onload = checkIfNormalizeOk();
		window.onload = initializeAnnotations();
        <?php if ($previous) {?>
            var fieldsetArray = document.getElementsByTagName('fieldset');
            var question = fieldsetArray[fieldsetArray.length - 1];
        <?php } elseif (isset($_GET['q'])) { ?>
            var fieldsetArray = document.getElementsByTagName('fieldset');
            for (var i = 0; i < fieldsetArray.length; i++) {
                if (fieldsetArray[i].getElementsByTagName('input')[0].getAttribute('name') == <?php echo $_GET['q']; ?>) {
                    var question = fieldsetArray[i];
                }
            }
        <?php } else { ?>
            var question = document.getElementsByTagName('fieldset')[0];
        <?php } ?>
        var itemNumber = question.getElementsByTagName('input')[0].getAttribute('name');
        document.getElementById('mark_button').setAttribute('currentItem', itemNumber);
        window.onload = focusForMarking(question);
    }
</script>
