<div class="row">
    <div class="col-sm-6">
        <h3>CONTACT US</h3>
        <p class="text-primary">If you are currently working with a Lenox Hill Premedical MCAT<sup>&reg;</sup> tutor, please contact them directly to schedule an appointment.</p><br/>
		<h4>LOCATION</h4>
		<p>The Stamford Innovation Center</br/>175 Atlantic Street. Stamford, CT 06901</p><br/>
		<h4>GENERAL INFORMATION</h4>
        <p>Please email Philip Murray.</p>
        <ul>
            <li><b>Email</b> - lenoxhillpremedical@gmail.com</li>
			<li><b>Phone</b> - <a href="tel:2035241189">(203) 524-1189</a></li>
        </ul>
    </div>
    <div class="col-sm-6">
    </div>
</div>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
