<div id="header"><table id="header_table"><tbody><tr><td>
                <div id="paginator">
                    <?php if (isset($paginationArray)) {
                        echo 'Questions ' . $paginationArray['min'] . '-' . $paginationArray['max'] . ' of ' . $paginationArray['total'];
                    } ?>
                </div>
            </td><td>
                <div id="logo_for_full_length_header">
                    <a style="color:white" href="/user"><i>LENOX HILL PREMEDICAL</i></a>
                </div>
            </td><td>
                <div id="timer"></div>
            </td></tr></tbody></table>
</div>
<div style="position:absolute;width:34%;top:100px;bottom:100px;left:33%;">
    <h2 style="text-align:center; margin:auto;"><?php echo $section->sectionName; ?></h2>
    <p style="text-align:center; font-weight: bold;">
        Number of Items: <?php echo $section->numberOfItems; ?><br/>
    </p>
    <?php if ($section->sectionName == \Model\McatSection::CRIT_SECTION_NAME) {;?>
        <p style="margin:auto; text-align: justify;"><b>DIRECTIONS:</b>
            There are nine passages in the <?php echo \Model\McatSection::CRIT_SECTION_NAME; ?> section. Each passage is
            followed by several questions. After reading a passage, select the one best answer to each question. If you
            are not certain of an answer, eliminate the alternatives that you know to be incorrect and then select an answer from
            the remaining alternatives. Indicate your selection by clicking on the answer bubble next to it.
        </p>
    <?php } else {;?>
        <p style="margin:auto; text-align: justify;"><b>DIRECTIONS:</b> Most questions in the <?php echo $section->sectionName; ?> section
            are organized into groups, each preceded by a descriptive passage. After studying the passage, select the one best answer to each question in
            the group. Some questions are not based on a descriptive passage and are also independent of each other. You must select the one best answer to
            these questions. If you are not certain of an answer, eliminate the alternatives that you know to be incorrect and then select an answer from the
            remaining alternatives. Indicate your selection by clicking on the answer bubble next to it. A periodic table is provided for your use. You may
            consult it whenever you wish.
        </p>
    <?php }; ?>
    <p style="margin:auto; text-align: justify;"><br/><br/>
        Click the "Next" button to see the first question of the <?php echo $section->sectionName; ?> section.
    </p>
</div>
<div id="footer">
    <form action="/full-length/directions-page/<?php echo $examId.'/'.$fullLengthNumber.'/'.$pageNumber; ?>" method="post">
        <input class="mcat_submit_button" type="submit" name="next" value="NEXT">
        <input type="hidden" name="timeRemaining" value="<?php echo $timeRemaining; ?>">
    </form>
</div>