<div class="row">
	<div class="col-sm-6">
		<h3>MCAT<sup>&reg;</sup> TUTORS</h3>
        <p>If you have a passion for teaching MCAT<sup>&reg;</sup>, we would like to meet you. Our mission is to
            attract the nation's most dedicated MCAT<sup>&reg;</sup> teachers and tutors. As MCAT<sup>&reg;</sup>
            instructors, we value MCAT<sup>&reg;</sup> expertise, patience, and compassion. Our organizational structure
            is innovative and teacher-friendly (hint: no bosses or managers). We understand the immense challenge
            of mastering MCAT<sup>&reg;</sup> material and teaching it. If you would welcome such a challenge, <i>we want you!</i>
            If you are interested in teaching or tutoring with us, please email Philip Murray at pmurray@lenoxhillpremedical.com and
            tell us your story. <i>Do not</i> send us a resum&eacute; or cover letter.
        </p>

        <h3>MCAT<sup>&reg;</sup> WRITERS</h3>
        <p>If you have a passion for MCAT<sup>&reg;</sup> and writing, we would like to meet you. Our mission is to
            create the nation's most accurate MCAT<sup>&reg;</sup> practice tests. As MCAT<sup>&reg;</sup>
            writers, we value MCAT<sup>&reg;</sup> expertise, patience, and compassion. Our organizational structure
            is innovative and writer-friendly (hint: no bosses or managers). We understand the immense challenge
            of mastering MCAT<sup>&reg;</sup> material and writing high quality passages. If you would welcome such a challenge, <i>we want you!</i>
            If you are interested in writing for us, please email Philip Murray at pmurray@lenoxhillpremedical.com and
            tell us your story. <i>Do not</i> send us a resum&eacute; or cover letter.
        </p><br/>
        <p><button class="btn btn-info btn-sm" data-toggle="modal" data-target="#biologyAuthor">
                BIOLOGY/BIOCHEMISTRY WRITER
            </button></p>
        <p><button class="btn btn-info btn-sm" data-toggle="modal" data-target="#chemistryAuthor">
                CHEMISTRY/PHYSICS WRITER
            </button></p>
        <p><button class="btn btn-info btn-sm" data-toggle="modal" data-target="#psychologyAuthor">
                PSYCHOLOGY/SOCIOLOGY WRITER
            </button></p>
        <p><button class="btn btn-info btn-sm" data-toggle="modal" data-target="#criticalReadingAuthor">
                NON-FICTION ENGLISH WRITER
            </button></p>


        <div class="modal fade" id="biologyAuthor" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="myModalLabel">BIOLOGY/BIOCHEMSITRY WRITER</h4>
                    </div>
                    <div class="modal-body">
                        <p>We are looking for a writer proficient in introductory college level biology and biochemistry
                            who can help our team write MCAT<sup>&reg;</sup> passages and question sets for our full-length MCAT<sup>&reg;</sup> practice tests.</p><br/>
                        <p><b>On a day-to-day basis, you will be:</b></p>
                        <ul>
                            <li>Researching and writing MCAT<sup>&reg;</sup> passages, question sets, and explanations for the Biology/Biochemistry
                                section of the new MCAT<sup>&reg;</sup>.</li>
                            <li>Working as an independent contractor:
                                <ul><li>From home or at our office, whichever you prefer.</li>
                                    <li>At your leisure, there are no due dates.</li>
                                </ul>
                            </li>
                        </ul><br/>
                        <p><b>Requirements:</b></p>
                        <ul>
                            <li>Completion of introductory college level Biology and Biochemistry.</li>
                            <li>Willingness to complete our 2-day training course on MCAT<sup>&reg;</sup> passage writing.</li>
                            <li>A passion for biology and medicine and a love of teaching and learning.</li>
                        </ul><br/>
                        <p>If you are interested, please email Philip Murray at pmurray@lenoxhillpremedical.com and tell us your story. Please
                            DO NOT send a resum&eacute; or cover letter.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="chemistryAuthor" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="myModalLabel">CHEMISTRY/PHYSICS WRITER</h4>
                    </div>
                    <div class="modal-body">
                        <p>We are looking for a writer proficient in introductory college chemistry, physics, and biology
                            who can help our team write MCAT<sup>&reg;</sup> passages and question sets for our full-length MCAT<sup>&reg;</sup> practice tests.</p><br/>
                        <p><b>On a day-to-day basis, you will be:</b></p>
                        <ul>
                            <li>Researching and writing MCAT<sup>&reg;</sup> passages, question sets, and explanations for the Chemistry/Physics
                                section of the new MCAT<sup>&reg;</sup>.</li>
                            <li>Working as an independent contractor:
                                <ul><li>From home or at our office, whichever you prefer.</li>
                                    <li>At your leisure, there are no due dates.</li>
                                </ul>
                            </li>
                        </ul><br/>
                        <p><b>Requirements:</b></p>
                        <ul>
                            <li>Completion of introductory college level Biology, Chemistry, and Physics.</li>
                            <li>Willingness to complete our 2-day training course on MCAT<sup>&reg;</sup> passage writing.</li>
                            <li>A passion for chemistry, physics and medicine and a love of teaching and learning.</li>
                        </ul><br/>
                        <p>If you are interested, please email Philip Murray at pmurray@lenoxhillpremedical.com and tell us your story. Please
                            DO NOT send a resum&eacute; or cover letter.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="psychologyAuthor" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="myModalLabel">PSYCHOLOGY/SOCIOLOGY WRITER</h4>
                    </div>
                    <div class="modal-body">
                        <p>We are looking for a writer proficient in introductory college psychology, sociology, and biology
                            who can help our team write MCAT<sup>&reg;</sup> passages and question sets for our full-length MCAT<sup>&reg;</sup> practice tests.</p><br/>
                        <p><b>On a day-to-day basis, you will be:</b></p>
                        <ul>
                            <li>Researching and writing MCAT<sup>&reg;</sup> passages, question sets, and explanations for the Psychology/Sociology
                                section of the new MCAT<sup>&reg;</sup>.</li>
                            <li>Working as an independent contractor.
                                <ul><li>From home or at our office, whichever you prefer.</li>
                                    <li>At your leisure, there are no due dates.</li>
                                </ul>
                            </li>
                        </ul><br/>
                        <p><b>Requirements:</b></p>
                        <ul>
                            <li>Completion of introductory college level Psychology, Sociology, and Biology.</li>
                            <li>Willingness to complete our 2-day training course on MCAT<sup>&reg;</sup> passage writing.</li>
                            <li>A passion for chemistry, physics and medicine and a love of teaching and learning.</li>
                        </ul><br/>
                        <p>If you are interested, please email Philip Murray at pmurray@lenoxhillpremedical.com and tell us your story. Please
                            DO NOT send a resum&eacute; or cover letter.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="criticalReadingAuthor" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="myModalLabel">NON-FICTION ENGLISH WRITER</h4>
                    </div>
                    <div class="modal-body">
                        <p>We are looking for a writer with a passion for non-fiction
                            who can help our team write MCAT<sup>&reg;</sup> Critical Reading passages and question sets for our full-length MCAT<sup>&reg;</sup> practice tests.</p><br/>
                        <p><b>On a day-to-day basis, you will be:</b></p>
                        <ul>
                            <li>Researching and writing MCAT<sup>&reg;</sup> passages, question sets, and explanations for the Critical Reading
                                section of the new MCAT<sup>&reg;</sup>.</li>
                            <li>Working as an independent contractor:
                                <ul><li>From home or at our office, whichever you prefer.</li>
                                    <li>At your leisure, there are no due dates.</li>
                                </ul>
                            </li>
                        </ul><br/>
                        <p><b>Requirements:</b></p>
                        <ul>
                            <li>A passion for non-fiction writing and a love of teaching and learning.</li>
                            <li>Willingness to complete our 2-day training course on MCAT<sup>&reg;</sup> passage writing.</li>
                        </ul><br/>
                        <p>If you are interested, please email Philip Murray at pmurray@lenoxhillpremedical.com and tell us your story. Please
                            DO NOT send a resum&eacute; or cover letter.
                        </p>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>

