<script type="text/javascript">
    function clickIAgree() {
        var pageArray = document.getElementsByClassName('examineeAgreementPage');
        for (var i = 0; i < 5; i++) {
            if (pageArray[i].style.display == 'block') {
                var currentPage = i;
                if (currentPage == 4) {
                    return;
                }
                var paginator = document.getElementById('paginator');
                paginator.innerHTML = 'Page ' + (currentPage+2) + ' of 5';
            }
        }
        for (var i = 0; i < 5; i++) {
            pageArray[i].style.display = 'none';
        }
        pageArray[currentPage + 1].style.display = 'block';
        return false;
    }
</script>
<div id="header"><table id="header_table"><tbody><tr><td>
                <div id="paginator">
					Page 1 of 5
                </div>
            </td><td>
                <div id="logo_for_full_length_header">
                    <a style="color:white" href="/user"><i>LENOX HILL PREMEDICAL</i></a>
                </div>
            </td><td>
                <div id="timer"></div>
            </td></tr></tbody></table>
</div>
    <div class="tutorial_page">
        <div class="examineeAgreementPage" style="display:block">
                <h1>WARNING:</h1>
                <p style="margin: 20px auto;">When you take the actual MCAT<sup>&reg;</sup>, the following items and behaviors will be strictly prohibited both during the exam and during breaks.</p>
                <p style="margin: 20px auto;"><img style="float:left; margin-right:10px;" src="/public/images/no_cell_phones.png"><span style="line-height:70px;">Electronic devices, including cellular phones.</span></p>
                <p style="margin: 20px auto;"><img style="float:left; margin-right:10px;" src="/public/images/no_cameras.png"><span style="line-height:70px;">Recording equipment of any kind.</span></p>
                <p style="margin: 20px auto;"><img style="float:left; margin-right:10px;" src="/public/images/no_books.png"><span style="line-height:70px;">Books, notes, or study materials of any kind.</span></p>
                <p style="margin: 20px auto;"><img style="float:left; margin-right:10px;" src="/public/images/no_talking.png"><span>Disruptive or abusive behavior. Talking in the testing room
  with anyone other than a proctor. Talking about or discussing the exam during a break.</span></p>
                <p style="margin: 50px auto; ">By clicking I AGREE, you acknowledge that you have read and understood the rules above. When you take the actual MCAT<sup>&reg;</sup>, possession of any
                    prohibited item or exhibition of any prohibited behavior will be considered an intentional breach
                    of MCAT<sup>&reg;</sup> security policies.
                </p>
        </div>
        <div class="examineeAgreementPage" style="display:none">
            <h2>INDEPENDENCE OF LENOX HILL PREMEDICAL AND THE ASSOCIATION OF AMERICAN MEDICAL COLLEGES (AAMC).</h2>
            <p>An integral component of the validity of the MCAT<sup>&reg;</sup> is the permanent independence between the creators of the MCAT<sup>&reg;</sup> (the AAMC),
                and the MCAT<sup>&reg;</sup> preparation entities (e.g. Lenox Hill Premedical). By clicking I AGREE, you certify that you have read and acknowledged the
                following statements:
            </p>
            <ul>
                <li><p>MCAT<sup>&reg;</sup> is a registered trademark of the AAMC. The AAMC is the creator of the MCAT<sup>&reg;</sup>
                    and is the <i>sole</i> authority on <i>every</i> aspect of the MCAT<sup>&reg;</sup>.</p></li>
                <li><p>The AAMC does not endorse <i>any</i> of the contents of this practice exam and was not involved in the creation
                    of its contents in <i>any</i> way.</p></li>
                <li><p>This practice test was created by, and is owned by, Lenox Hill Premedical.</p></li>
            </ul>
        </div>
        <div class="examineeAgreementPage" style="display:none">
            <h2>EXAMINEE AGREEMENT AND GENERAL TERMS OF USE FOR THIS EXAMINATION.</h2>
            <p>Before you continue with this exam, you must agree to each of the following statements by clicking I AGREE.</p>
            <ul>
                <li><p>I certify that I am the person whose name and email is associated with this Lenox Hill Premedical account.</p></li>
                <li><p>I understand that the contents of this examination are licensed to me and only me. I understand that Lenox Hill Premedical can and will
                        monitor the activity of my Lenox Hill Premedical account. If it is discovered that persons other than myself are accessing my account
                        for the purpose of taking this exam, this constitutes a violation of the examinee agreement, and Lenox Hill Premedical has the right to
                        terminate my account without notice and without issuing a refund.</p>
                </li>
            </ul>
        </div>
        <div class="examineeAgreementPage" style="display:none">
            <h2>ACCURACY OF ESTIMATED SCORES.</h2>
            <p>Upon completion of this practice MCAT, you will have the option to receive an estimated scaled score based on your performance.
            The scaling algorithms created by Lenox Hill Premedical were designed to predict your score on the actual MCAT to within 2 points. However, by
                clicking I AGREE, you acknowledge the following statements.</p>
            <ul>
                <li><p>The score-scaling algorithms used on the actual MCAT are owned by the AAMC and are not publicly available.</p></li>
                <li><p>The score-scaling algorithms used to produce a scaled score (472 - 528) for this practice MCAT
                        were created by, and are owned by, Lenox Hill Premedical.</p>
                </li>
                <li><p>Lenox Hill Premedical does not guarantee that identical performances on this test and on the actual
                    MCAT will result in identical scaled scores.</p></li>
            </ul>

        </div>
        <div class="examineeAgreementPage" style="display:none">
            <h2>COPYRIGHT<sup>&copy;</sup> BY LENOX HILL PREMEDICAL.</h2>
            By clicking I AGREE, you acknowledge the following statements:
                <ul><li><p>The contents of the practice MCAT you are about to take are copyrighted, and
                    they are protected by United States and international copyright and trade secret laws.</p></li>
                <li><p>No part of this practice MCAT may be reproduced, distributed, or transmitted in any form or by any means,
                    including copy/pasting, photocopying, recording, or other electronic or mechanical methods, without the prior written
                    permission of Lenox Hill Premedical, except in the case of brief quotations embodied in critical reviews and
                    certain other noncommercial uses permitted by copyright law.</p></li>
                    </ul>
        </div>
    </div>
<div id="footer">
    <form action="/full-length/examineeagreement-page/<?php echo $examId.'/'.$fullLengthNumber.'/'.$pageNumber; ?>" method="post">
        <input class="mcat_submit_button" type="submit" name="iAgree" value="I AGREE" onclick="return clickIAgree();">
        <input type="hidden" name="timeRemaining" value="<?php echo $timeRemaining; ?>">
    </form>
</div>