<div id="header"><table id="header_table"><tbody><tr><td>
                <div id="paginator">
                    <?php if (isset($paginationArray)) {
                        echo 'Questions ' . $paginationArray['min'] . '-' . $paginationArray['max'] . ' of ' . $paginationArray['total'];
                    } ?>
                </div>
            </td><td>
                <div id="logo_for_full_length_header">
                    <a style="color:white" href="/user"><i>LENOX HILL PREMEDICAL</i></a>
                </div>
            </td><td>
                <div id="timer"></div>
            </td></tr></tbody></table>
</div>
<div style="position:fixed;top:20%;bottom:30%;width:50%;left:25%">
        <h3 style="height:10%;text-align:center;">
			You have chosen to have your MCAT scored.
		</h3>
		<span style="display:block;padding-top:10%;padding-bottom:10%;border:2px solid black;text-align:center;font-size:1.5em;">
			<?php echo $firstName.' '.$lastName; ?>
		</span>
		<p style="text-align:center;">Click <a style="color:blue" href="/user">here</a> to review your MCAT and see your score.</p>
</div>  
    <div style="margn:auto; text-align:center">
        <div style="width:700px; margin:auto;">
        </div>
    </div>
<div id="footer">
</div>