<!DOCTYPE html>
<html>
<head>
    <title>Full-Length MCAT</title>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <!-- Styles -->
    <link href="/public/images/favicon.ico" rel="shortcut icon">
    <link href="/public/css/full-length.css" rel="stylesheet">
    <!-- Scripts -->
    <script src="/public/js/mark.js"></script>
    <script src="/public/js/timer.js"></script>
</head>

<body>
<?php echo $content; ?>

<script type="text/javascript">
    if (document.forms[0].elements['timeRemaining']) {
        window.onload = CreateTimer("timer", document.forms[0].elements['timeRemaining'].value);
    }
</script>
</body>
</html>
