<!DOCTYPE html>
<html>
    <head>
        <title>Full-Length MCAT Review</title>
			<meta http-equiv="content-type" content="text/html;charset=utf-8" />
        <!-- Styles -->
        <link href="/public/images/favicon.ico" rel="shortcut icon">
        <link href="/public/css/full-length.css" rel="stylesheet">
        <!-- Scripts -->
        <script src="/public/js/mark.js"></script>
    </head>

    <body>
        <?php echo $content; ?>
    </body>
</html>