<div class="container-fluid">
      <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="10000">
        <div class="carousel-inner">
            <div class="item active">
                <img class="img-rounded img-thumbnail img-responsive" src="public/images/mhm_landing_page_image_1.jpg">
                <div class="carousel-caption">
                    <h3>Welcome to Lenox Hill Premedical<br/>
                     <small style="color:white">Preparing Connecticut's Future Doctors for the MCAT<sup>&reg;</sup></small><br/><br/><br/>
                    </h3>
                </div>
            </div>
			<div class="item">
                <img class="img-rounded img-thumbnail img-responsive" src="public/images/mhm_landing_page_image_5.jpg">
                <div class="carousel-caption">
                    <h3>&Agrave; La Carte MCAT<sup>&reg;</sup> Classes<br/>
                     <small style="color:white">Instructed live at Connecticut's<br/>colleges and universities.</small><br/><br/>
                    </h3>
                </div>
            </div>
            <div class="item">
                <img class="img-rounded img-thumbnail img-responsive"src="public/images/mhm_landing_page_image_3.jpg">
                <div class="carousel-caption">
                    <h3>Full-length Practice MCAT<sup>&reg;</sup>s<br/>
                     <small style="color:white">With accurate scores and explanations.</small><br/><br/><br/>
                    </h3>
                </div>
            </div>
            <div class="item">
                <img class="img-rounded img-thumbnail img-responsive" src="public/images/mhm_landing_page_image_4.jpg">
                <div class="carousel-caption">
                    <h3 style="color:white">MCAT<sup>&reg;</sup> Industry Experts<br/>
                    </h3>
                </div>
            </div>
        </div>
      </div>
</div>
<div class="container-fluid;">
	<div class="row" style="margin:20px;">
		<div class="col-sm-12 text-center">
			<a href="user/login?beginFreeMcat=true" class="btn btn-lg btn-success">BEGIN FREE MCAT<sup>&reg;</sup></a>
		</div>
	</div>
</div>
<div class="container-fluid">
    <div class="row" style="padding:10px;">
		<div class="col-sm-2"></div>
        <div class="col-sm-4 text-center">
             <h3>MCAT<sup>&reg;</sup> Classes in Connecticut<br/></h3>
             <span style="display:block;"><a href="mcat-classes" class="btn btn-info">Find a Class</a></span>
        </div>
        <div class="col-sm-4 text-center">
            <h3>Full-length Practice Tests</h3>
            <span style="display:block;"><a href="practice-tests" class="btn btn-large btn-info">Learn More</a></span>
        </div>
		<div class="col-sm-2"></div>
    </div>
</div>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
