<div class="row">
 <div class="col-sm-6">
	<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="10000">	        
	   <div class="carousel-inner">
	      <div class="item active">
	          <img class="img-rounded img-thumbnail img-responsive" src="public/images/mhm_internships_1.jpg">
	            <div class="carousel-caption">
	               <h2>
	                 <small style="color:white"></small>
	               </h2>
	            </div>
	      </div>
	      <div class="item">
	         <img class="img-rounded img-thumbnail img-responsive" src="public/images/mhm_internships_2.jpg">
	            <div class="carousel-caption">
	              <h3>
	                 <small style="color:white"></small>
	              </h3>
	         </div>
	      </div>
	      <div class="item">
	            <img class="img-rounded img-thumbnail img-responsive"src="public/images/mhm_internships_3.jpg">
	              <div class="carousel-caption">
	                <h3>
	                  <small style="color:white"></small>
	                </h3>
	            </div>
	      </div>
	   </div>
	 </div>
	 	<br/><br/><br/>
		<div class="text-center">
			<h4 class="text-info">INTERNSHIP SNIPPETS</h4>
		</div>
		<div class="text-center"><img class="img-rounded img-thumbnail" src="<?php echo $bucket; ?>internship_snippet_1.jpg"></div><br/><br/>
		<div class="text-center"><img class="img-rounded img-thumbnail" src="<?php echo $bucket; ?>internship_snippet_2.jpg"></div><br/><br/>
		<div class="text-center"><img class="img-rounded img-thumbnail" src="<?php echo $bucket; ?>internship_snippet_3.jpg"></div><br/><br/>
		<div class="text-center"><img class="img-rounded img-thumbnail" src="<?php echo $bucket; ?>internship_snippet_4.jpg"></div><br/><br/>
		<div class="text-center"><img class="img-rounded img-thumbnail" src="<?php echo $bucket; ?>internship_snippet_5.jpg"></div><br/><br/>
 </div>
 <div class="col-sm-6">
 <h3>SUMMER INTERNSHIP PROGRAM</h3>
  <p>Lenox Hill Premedical’s summer internship program is designed for aspiring physicians who are planning to take the MCAT<sup>&reg;</sup> in less than 18 months. In this month-long program, interns join a team of like-minded premedical students and thoroughly prepare for their MCAT<sup>&reg;</sup> under the direct guidance of a Lenox Hill Premedical MCAT<sup>&reg;</sup> instructor. The mission of the internship program is to provide interns with a superior MCAT<sup>&reg;</sup> preparation experience while simultaneously allowing Lenox Hill Premedical MCAT<sup>&reg;</sup> instructors to hone their craft and test and rehearse the company’s new lessons and material.
  </p><br/>
  <h4>LOCATION</h4><p>The Stamford Innovation Center: 175 Atlantic St, Stamford CT 06901 (Ten minute walk from Stamford Metro North Station)</p><br/>
  <h4>START DATE</h4><p>Wednesday, June 8 2016</p><br/>
  <h4>END DATE</h4><p>Thursday, July 7 2016</p><br/>
  <h4>HOURS</h4><p>10:00 am - 4:00 pm Mondays through Thursdays</p><br/>
  <h4>ON A DAY-TO-DAY-BASIS, YOU WILL BE:</h4>
  <ul><li>Studying MCAT<sup>&reg;</sup> for at least 3 hours.</li>
  	  <li>Attending MCAT<sup>&reg;</sup> seminars and lessons.</li>
  	  <li>Giving presentations to your fellow interns.</li>
  	  <li>Counseling prospective MCAT<sup>&reg;</sup> examinees.</li>
  	  <li>Testing new MCAT<sup>&reg;</sup> preparation material and technologies produced by Lenox Hill Premedical.</li>
  </ul>
  </ul><br/>
  <h4>REQUIREMENTS:</h4>
  <ul>
   <li>You plan on taking the actual MCAT<sup>&reg;</sup> within the next 18 months.</li>
   <li>You have a teaching and learning style that is patient and understanding.</li>
   <li>You are committed to pursuing a career in medicine.</li>
   <li>You are willing to commute to Stamford, CT.</li>
  </ul><br/>
  <h4>SPECIFICS:</h4>
  <ul>
   <li>This is an unpaid internship.</li>
   <li>Interns are given priority consideration for employment opportunities.</li>
   <li>Medical school recommendations will be written for outstanding interns.</li>
  </ul><br/>
     <p>To apply for this internship, please email Philip Murray at pmurray@lenoxhillpremedical.com and tell us your story in two to three paragraphs. Please include a brief description of a doctor who inspired you. Please <i>do not</i> send a r&eacute;sum&eacute; or cover letter.
     </p>
 </div>
</div>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>



