<div id="header"><table id="header_table"><tbody><tr><td>
                <div id="paginator">
                    <?php if (isset($paginationArray)) {
                        echo 'Questions ' . $paginationArray['min'] . '-' . $paginationArray['max'] . ' of ' . $paginationArray['total'];
                    } ?>
                </div>
            </td><td>
                <div id="logo_for_full_length_header">
                    <a style="color:white" href="/user"><i>LENOX HILL PREMEDICAL</i></a>
                </div>
            </td><td>
                <div id="timer"></div>
            </td></tr></tbody></table>
</div>
<div style="position:fixed;top:20%;bottom:30%;width:50%;left:25%">
        <h1 style="height:10%;text-align:center;">
			Mid-Exam Break
		</h1>
		<span style="display:block;padding-top:10%;padding-bottom:10%;border:2px solid black;text-align:center;font-size:1.5em;">
			<?php echo $firstName.' '.$lastName; ?>
		</span>
		<p>You may take an extended break for the time displayed in the upper right hand corner of the screen.
        If you wish to continue with the next section of the exam before the time has elapsed,
        press the "END BREAK" button.</p>
</div>  
<div id="footer">
    <form action="/full-length/lunch-page/<?php echo $examId.'/'.$fullLengthNumber.'/'.$pageNumber; ?>" method="post">
        <input class="mcat_submit_button" type="submit" name="next" value="END BREAK">
        <input type="hidden" name="timeRemaining" value="<?php echo $timeRemaining; ?>">
    </form>
</div>