<?php $classCounter = 0; $bucket = getenv('LHP_SITE_BUCKET');?>
<script type="text/javascript">
    //window.onload = function() {$('#simulatedtest').modal('show')};
</script>
<div class="row">
 <div class="col-sm-6">
	<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="10000">
	   <div class="carousel-inner">
	      <div class="item active">
	          <img style="margin:auto;" class="img-rounded img-thumbnail img-responsive" src="public/images/mhm_internships_1.jpg">
	            <div class="carousel-caption">
	               <h2>
	                 <small style="color:white"></small>
	               </h2>
	            </div>
	      </div>
	      <div class="item">
	         <img style="margin:auto;" class="img-rounded img-thumbnail img-responsive" src="public/images/mcat_classes_2.jpg">
	            <div class="carousel-caption">
	              <h3>
	                 <small style="color:white"></small>
	              </h3>
	         </div>
	      </div>
	      <div class="item">
	            <img style="margin:auto;" class="img-rounded img-thumbnail img-responsive"src="public/images/mcat_classes_1.jpg">
	              <div class="carousel-caption">
	                <h3>
	                  <small style="color:white"></small>
	                </h3>
	            </div>
	      </div>
	   </div>
	</div><br/>
	<div class="text-center text-danger"><?php echo $flash['message']; ?></div>
	<div class="text-center text-success"><h1>Select a Class:</h1></div><br/>
	<div class="text-center text-success"><h4>MCAT<sup>&reg;</sup> SEMINARS</h4></div>
	<button class="btn btn-success mcat-menu" data-toggle="modal" data-target="#information">INFORMATION SESSION</button>
	<div class="modal fade" id="information" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> Information Session</h4>
				</div>
				<div class="modal-body">
					<?php foreach ($classes as $class) {
						if ($class['Topic'] == 'information') {$classCounter++; ?>
							<div class="row" style="border-bottom:1px solid lightgray; padding:10px;">
								<div class="col-sm-2" style="border-right:1px solid lightgray;">
									<div class="text-primary"><big><strong><?php echo strtoupper($class['Start']->format('M')); ?></strong></big><br/><?php echo $class['Start']->format('d, Y'); ?></div>
								</div>
								<div class="col-sm-10">
									<small><strong>Instructor:</strong> <?php echo $class['Instructor']; ?></span></small><br/>
									<small class="text-muted"><?php echo $class['Start']->format('g:ia').' - '.$class['End']->format('g:ia').' '.$class['Location']; ?></small><br/>
									<?php if ($class['AvailableSeats'] > 0) { ?>
										<small class="text-danger"><?php echo $class['AvailableSeats']; ?> tickets available</small><br/>
										<small style="color:green"><strong><?php echo ($class['Price'] == 0) ? 'FREE' : '$'.$class['Price'].'.00'; ?></strong></small> <a href="/class-registration?classId=<?php echo $class['ClassId']; ?>" style="color:white; text-decoration:none" class="btn btn-xs btn-success">Reserve Seat</a>
									<?php } else {?>
										<small class="text-danger">Class full<br/>No tickets available</small>
									<?php } ?>
								</div>
							</div>
					<?php }} if ($classCounter == 0) { ?>
						<p class="text-danger"><small>There are no MCAT<sup>&reg;</sup> information sessions currently scheduled. If you would like Lenox Hill Premedical to host an MCAT<sup>&reg;</sup> information session near your location, please email Philip Murray at lenoxhillpremedical@gmail.com or contact us at 203-524-1189.</small></p>
					<?php } else {$classCounter = 0;} ?>
					<br/><p>In this hour-long seminar, you will learn the fundamentals of the MCAT from a Lenox Hill Premedical instructor - everything from "What is the MCAT?" to the most recent changes and the test-day experience. This seminar is appropriate for anyone considering a career in medicine, from high school seniors to adult professionals. The topics covered include:</p>
						<ul style="font-size:0.8em;">
							<li><b>BASIC INFORMATION</b>
								<ul>
									<li>Why the MCAT exists</li>
									<li>Who makes the test</li>
									<li>How and when you should take the test</li>
								</ul>
							</li>
							<li><b>TEST DETAILS</b>
								<ul>
									<li>Topics covered</li>
									<li>Testing interface</li>
									<li>Number of questions</li>
									<li>Timing</li>
								</ul>
							</li>
							<li><b>ADMISSIONS STATISTICS</b>
								<ul>
									<li>How the MCAT is scored</li>
									<li>How MCAT scores are used in medical school admissions</li>
								</ul>
							</li>
							<li><b>PREPARING FOR THE MCAT</b>
								<ul>
									<li>When to begin preparing</li>
									<li>How to prepare</li>
									<li>Where to find resources</li>
								</ul>
							</li>
						</ul>
					<p>You will also have an opportunity to meet a Lenox Hill Premedical MCAT<sup>&reg;</sup> instructor and ask them specific questions.</p><br/>
					<h4 class="text-center">SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>information_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>information_snippet_2.jpg">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>information_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>information_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-success mcat-menu" data-toggle="modal" data-target="#practice">DRILL SESSION</button>
	<div class="modal fade" id="practice" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> Drill Session</h4>
				</div>
				<div class="modal-body">
					<?php foreach ($classes as $class) {
						if ($class['Topic'] == 'practice') {$classCounter++; ?>
							<div class="row" style="border-bottom:1px solid lightgray; padding:10px;">
								<div class="col-sm-2" style="border-right:1px solid lightgray;">
									<div class="text-primary"><big><strong><?php echo strtoupper($class['Start']->format('M')); ?></strong></big><br/><?php echo $class['Start']->format('d, Y'); ?></div>
								</div>
								<div class="col-sm-10">
									<small><strong>Instructor:</strong> <?php echo $class['Instructor']; ?></span></small><br/>
									<small class="text-muted"><?php echo $class['Start']->format('g:ia').' - '.$class['End']->format('g:ia').' '.$class['Location']; ?></small><br/>
									<?php if ($class['AvailableSeats'] > 0) { ?>
										<small class="text-danger"><?php echo $class['AvailableSeats']; ?> tickets available</small><br/>
										<small style="color:green"><strong><?php echo ($class['Price'] == 0) ? 'FREE' : '$'.$class['Price'].'.00'; ?></strong></small> <a href="/class-registration?classId=<?php echo $class['ClassId']; ?>" class="btn btn-xs btn-success" style="color:white; text-decoration:none">Reserve Seat</a></span>
									<?php } else {?>
										<small class="text-danger">Class full<br/>No tickets available</small>
									<?php } ?>
								</div>
							</div>
					<?php }} if ($classCounter == 0) { ?>
						<p class="text-danger"><small>There are no MCAT<sup>&reg;</sup> drill sessions currently scheduled. If you would like Lenox Hill Premedical to host a drill session near your location, please email Philip Murray at pmurray@lenoxhillpremedical.com or contact us at 203-524-1189.</small></p>
					<?php } else {$classCounter = 0;} ?>
						<br/><p>Drill sessions involve practicing MCAT<sup>&reg;</sup> passages and question sets with a Lenox Hill Premedical MCAT<sup>&reg;</sup> instructor.</p>
						<p>Similar to medical residents working with an attending physician on a new case, drill sessions allow you to work with an instructor on questions that are unscripted and unrehearsed. By doing this, you will get first-hand experience of how an MCAT<sup>&reg;</sup> expert:
						</p>
						<img style="float:right" class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>mcat_practice_session_snippet_1.jpg">
						<ol>
						 <li>Analyzes the passage.</li>
						 <li>Diagnoses the questions.</li>
						 <li>Manages timing.</li>
						 <li>Handles unfamiliar content.</li>
						 <li>Arrives at an answer choice.</li>
						</ol><br/>
						<p>Equally important, but less obvious, is how drill sessions allow you to <i>calibrate</i> your skill level by comparing yourself to your instructor. As you get deeper and deeper into your MCAT<sup>&reg;</sup> studying, you will begin to ask yourself questions like:</p>
						<img style="float:right;" class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>mcat_practice_session_snippet_2.jpg">
						<ul><li>"Is my acid/base chemistry knowledge good enough?"</li>
							<li>"Do I need to review the thin lens equation?"</li>
							<li>"Should I memorize the DSM-5 mental disorders?"</li>
							<li>"Am I prepared for a tough question on the structure of lipids?"</li>
						</ul>
						<br/>
						<p>Practicing passages at a drill session on a topic that is concerning you will allow you to quickly ascertain where you stand on that topic. For example, if you are outperforming the instructor on optics passages, and the instructor scored a 131 on the Chem/Phys section, then you can rest assured that you need not study any more optics! With this information comes piece of mind that your MCAT<sup>&reg;</sup> studying is on the right track.</p>
						<p>Once you have established a solid core of MCAT<sup>&reg;</sup> content knowledge, you will find that drill sessions of this type are the <i>single most effective</i> method of preparing for your MCAT<sup>&reg;</sup>.</p>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-success mcat-menu" data-toggle="modal" data-target="#simulatedtest">SIMULATED TEST</button>
	<div class="modal fade" id="simulatedtest" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">Simulated MCAT<sup>&reg;</sup></h4>
				</div>
				<div class="modal-body">
					<?php foreach ($classes as $class) {
						if ($class['Topic'] == 'simulatedtest') {$classCounter++; ?>
							<div class="row" style="border-bottom:1px solid lightgray; padding:10px;">
								<div class="col-sm-2" style="border-right:1px solid lightgray;">
									<div class="text-primary"><big><strong><?php echo strtoupper($class['Start']->format('M')); ?></strong></big><br/><?php echo $class['Start']->format('d, Y'); ?></div>
								</div>
								<div class="col-sm-10">
									<small><strong>Instructor:</strong> <?php echo $class['Instructor']; ?></span></small><br/>
									<small class="text-muted"><?php echo $class['Start']->format('g:ia').' - '.$class['End']->format('g:ia').' '.$class['Location']; ?></small><br/>
									<?php if ($class['AvailableSeats'] > 0) { ?>
										<small class="text-danger"><?php echo $class['AvailableSeats']; ?> tickets available</small><br/>
										<small style="color:green"><strong><?php echo ($class['Price'] == 0) ? 'FREE' : '$'.$class['Price'].'.00'; ?></strong></small> <a href="/class-registration?classId=<?php echo $class['ClassId']; ?>" class="btn btn-xs btn-success" style="color:white; text-decoration:none">Reserve Seat</a></span>
									<?php } else {?>
										<small class="text-danger">Class full<br/>No tickets available</small>
									<?php } ?>
								</div>
							</div>
					<?php }} if ($classCounter == 0) { ?>
						<p class="text-danger"><small>There are no Simulated Tests currently scheduled. If you would like Lenox Hill Premedical to host a practice MCAT<sup>&reg;</sup> near your location, please email Philip Murray at pmurray@lenoxhillpremedical.com or contact us at 203-524-1189.</small></p>
					<?php } else {$classCounter = 0;} ?>
						<br/><p>Simulated tests allow you to take a practice MCAT<sup>&reg;</sup> under test-day-like conditions and receive a scaled score and detailed explanations for all correct and incorrect answers. Lenox Hill Premedical offers three types of simulated tests:
						<ul style="font-size:0.8em;">
								<li><b>QUARTER LENGTH</b>
									<ul>
										<li>Seat time: 1 hour 35 minutes</li>
										<li>Total testing time: 2 hours</li>
										<li>Sections: Any <i>one</i> MCAT section of your choice (Chem/Phys, Bio/Biochem, CARS, Psych/Soc)</li>
									</ul>
								</li>
								<li><b>HALF LENGTH</b>
									<ul>
										<li>Seat time: 3 hours 10 minutes</li>
										<li>Total testing time: 3 hours 30 minutes</li>
										<li>Sections: Any <i>two</i> MCAT sections of your choice (Chem/Phys, Bio/Biochem, CARS, Psych/Soc)</li>
									</ul>
								</li>
								<li><b>FULL LENGTH</b>
									<ul>
										<li>Seat time: 6 hours 15 minutes</li>
										<li>Total testing time: 7 hours</li>
										<li>Sections: All</li>
									</ul>
								</li>
							</ul>
					<h4 class="text-center">SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>mhm_simulated_mcats_2.jpg">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>mhm_simulated_mcats_5.jpg">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>mhm_simulated_mcats_6.jpg">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>mhm_simulated_mcats_1.jpg">
					</div>
				</div>
			</div>
		</div>
	</div>
	<br/><br/>
	<div class="text-center text-success"><h4>CONTENT LESSONS</h4></div>
	<button class="btn btn-success mcat-menu" data-toggle="modal" data-target="#physics1">PHYSICS 1</button>
	<div class="modal fade" id="physics1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<div class="modal-title text-center" id="myModalLabel"><h4>MCAT<sup>&reg;</sup> PHYSICS 1</h4><h5>Kinematics, Forces, Energy, Periodic Motion, and Fluids</h5></div>
				</div>
				<div class="modal-body">
					<?php foreach ($classes as $class) {
						if ($class['Topic'] == 'physics1') {$classCounter++; ?>
							<div class="row" style="border-bottom:1px solid lightgray; padding:10px;">
								<div class="col-sm-2" style="border-right:1px solid lightgray;">
									<div class="text-primary"><big><strong><?php echo strtoupper($class['Start']->format('M')); ?></strong></big><br/><?php echo $class['Start']->format('d, Y'); ?></div>
								</div>
								<div class="col-sm-10">
									<small><strong>Instructor:</strong> <?php echo $class['Instructor']; ?></span></small><br/>
									<small class="text-muted"><?php echo $class['Start']->format('g:ia').' - '.$class['End']->format('g:ia').' '.$class['Location']; ?></small><br/>
									<?php if ($class['AvailableSeats'] > 0) { ?>
										<small class="text-danger"><?php echo $class['AvailableSeats']; ?> tickets available</small><br/>
										<small style="color:green"><strong><?php echo ($class['Price'] == 0) ? 'FREE' : '$'.$class['Price'].'.00'; ?></strong></small> <a href="/class-registration?classId=<?php echo $class['ClassId']; ?>" class="btn btn-xs btn-success" style="color:white; text-decoration:none">Reserve Seat</a></span>
									<?php } else {?>
										<small class="text-danger">Class full<br/>No tickets available</small>
									<?php } ?>
								</div>
							</div>
					<?php }} if ($classCounter == 0) { ?>
						<p class="text-danger"><small>There are no MCAT<sup>&reg;</sup> Physics 1 classes currently scheduled. If you would like Lenox Hill Premedical to host a class near your location, please email Philip Murray at pmurray@lenoxhillpremedical.com or contact us at 203-524-1189.</small></p>
					<?php } else {$classCounter = 0;} ?>
						<br/><p>In this 3-hour lesson, you will learn the MCAT<sup>&reg;</sup>-relevant content for the first half of introductory, college-level physics. Topics include the laws of motion, Newton's laws of forces, the relationship between work and energy, torque, simple harmonic motion, radioactive decay, and fluid dynamics. You will learn these physics topics at the same level of depth tested on the MCAT<sup>&reg;</sup>, and your instructor will teach you the most common ways these topics will present themselves on the test.</p><br/>
					<h4 class="text-center">LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>physics_1_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>physics_1_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>physics_2_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>physics_2_snippet_3.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-success mcat-menu" data-toggle="modal" data-target="#physics2">PHYSICS 2</button>
	<div class="modal fade" id="physics2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> PHYSICS 2<br/>Nuclear Physics, Fluids, Solids, and Wave Mechanics</h4>
				</div>
				<div class="modal-body">
					<?php foreach ($classes as $class) {
						if ($class['Topic'] == 'physics2') {$classCounter++; ?>
							<div class="row" style="border-bottom:1px solid lightgray; padding:10px;">
								<div class="col-sm-2" style="border-right:1px solid lightgray;">
									<div class="text-primary"><big><strong><?php echo strtoupper($class['Start']->format('M')); ?></strong></big><br/><?php echo $class['Start']->format('d, Y'); ?></div>
								</div>
								<div class="col-sm-10">
									<small><strong>Instructor:</strong> <?php echo $class['Instructor']; ?></span></small><br/>
									<small class="text-muted"><?php echo $class['Start']->format('g:ia').' - '.$class['End']->format('g:ia').' '.$class['Location']; ?></small><br/>
									<?php if ($class['AvailableSeats'] > 0) { ?>
										<small class="text-danger"><?php echo $class['AvailableSeats']; ?> tickets available</small><br/>
										<small style="color:green"><strong><?php echo ($class['Price'] == 0) ? 'FREE' : '$'.$class['Price'].'.00'; ?></strong></small> <a href="/class-registration?classId=<?php echo $class['ClassId']; ?>" class="btn btn-xs btn-success" style="color:white; text-decoration:none">Reserve Seat</a></span>
									<?php } else {?>
										<small class="text-danger">Class full<br/>No tickets available</small>
									<?php } ?>
								</div>
							</div>
					<?php }} if ($classCounter == 0) { ?>
						<p class="text-danger"><small>There are no MCAT<sup>&reg;</sup> Physics 2 classes currently scheduled. If you would like Lenox Hill Premedical to host a class near your location, please email Philip Murray at pmurray@lenoxhillpremedical.com or contact us at 203-524-1189.</small></p>
					<?php } else {$classCounter = 0;} ?>
						<p>In this lesson, you will learn the MCAT<sup>&reg;</sup>-relevant content for the second half of introductory, college-level physics. The topics are properties of solids, fundamentals of mechanical waves, electrostatics, magnetism, the right hand rule, DC/AC circuits, and the fundamentals of light and optics. You will learn these physics topics at the same level of depth tested on the MCAT<sup>&reg;</sup>, focusing on the most common ways they present themselves on the MCAT<sup>&reg;</sup></p><br/>
					<h4 class="text-center">LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>physics_3_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>physics_2_snippet_4.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>physics_3_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>physics_3_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-success mcat-menu" data-toggle="modal" data-target="#genchem1">GENERAL CHEMISTRY 1</button>
	<div class="modal fade" id="genchem1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> GENERAL CHEMISTRY 1<br/>Periodic Trends, Quantum Mechanics, and Gases</h4>
				</div>
				<div class="modal-body">
					<?php foreach ($classes as $class) {
						if ($class['Topic'] == 'genchem1') {$classCounter++; ?>
							<div class="row" style="border-bottom:1px solid lightgray; padding:10px;">
								<div class="col-sm-2" style="border-right:1px solid lightgray;">
									<div class="text-primary"><big><strong><?php echo strtoupper($class['Start']->format('M')); ?></strong></big><br/><?php echo $class['Start']->format('d, Y'); ?></div>
								</div>
								<div class="col-sm-10">
									<small><strong>Instructor:</strong> <?php echo $class['Instructor']; ?></span></small><br/>
									<small class="text-muted"><?php echo $class['Start']->format('g:ia').' - '.$class['End']->format('g:ia').' '.$class['Location']; ?></small><br/>
									<?php if ($class['AvailableSeats'] > 0) { ?>
										<small class="text-danger"><?php echo $class['AvailableSeats']; ?> tickets available</small><br/>
										<small style="color:green"><strong><?php echo ($class['Price'] == 0) ? 'FREE' : '$'.$class['Price'].'.00'; ?></strong></small> <a href="/class-registration?classId=<?php echo $class['ClassId']; ?>" class="btn btn-xs btn-success" style="color:white; text-decoration:none">Reserve Seat</a></span>
									<?php } else {?>
										<small class="text-danger">Class full<br/>No tickets available</small>
									<?php } ?>
								</div>
							</div>
					<?php }} if ($classCounter == 0) { ?>
						<p class="text-danger"><small>There are no MCAT<sup>&reg;</sup> General Chemistry 1 classes currently scheduled. If you would like Lenox Hill Premedical to host a class near your location, please email Philip Murray at pmurray@lenoxhillpremedical.com or contact us at 203-524-1189.</small></p>
					<?php } else {$classCounter = 0;} ?>
						<br/><p>In this 3-hour lesson, you will learn the MCAT<sup>&reg;</sup>-relevant content for the first third of introductory, college-level general chemistry. Topics include atomic structure, periodicity, quantum mechanics, and the kinetic molecular theory of gases. You will learn these chemistry topics at the same level of depth tested on the MCAT<sup>&reg;</sup>, and your instructor will teach you the most common ways these topics will present themselves on the test.</p><br/>
					<h4 class="text-center">LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>general_chemistry_1_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>general_chemistry_1_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>general_chemistry_1_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>general_chemistry_1_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-success mcat-menu" data-toggle="modal" data-target="#genchem2">GENERAL CHEMISTRY 2</button>
	<div class="modal fade" id="genchem2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> GENERAL CHEMISTRY 2<br/>Thermodynamics, Solutions, and Colligative Properties</h4>
				</div>
				<div class="modal-body">
					<?php foreach ($classes as $class) {
						if ($class['Topic'] == 'genchem2') {$classCounter++; ?>
							<div class="row" style="border-bottom:1px solid lightgray; padding:10px;">
								<div class="col-sm-2" style="border-right:1px solid lightgray;">
									<div class="text-primary"><big><strong><?php echo strtoupper($class['Start']->format('M')); ?></strong></big><br/><?php echo $class['Start']->format('d, Y'); ?></div>
								</div>
								<div class="col-sm-10">
									<small><strong>Instructor:</strong> <?php echo $class['Instructor']; ?></span></small><br/>
									<small class="text-muted"><?php echo $class['Start']->format('g:ia').' - '.$class['End']->format('g:ia').' '.$class['Location']; ?></small><br/>
									<?php if ($class['AvailableSeats'] > 0) { ?>
										<small class="text-danger"><?php echo $class['AvailableSeats']; ?> tickets available</small><br/>
										<small style="color:green"><strong><?php echo ($class['Price'] == 0) ? 'FREE' : '$'.$class['Price'].'.00'; ?></strong></small> <a href="/class-registration?classId=<?php echo $class['ClassId']; ?>" class="btn btn-xs btn-success" style="color:white; text-decoration:none">Reserve Seat</a></span>
									<?php } else {?>
										<small class="text-danger">Class full<br/>No tickets available</small>
									<?php } ?>
								</div>
							</div>
					<?php }} if ($classCounter == 0) { ?>
						<p class="text-danger"><small>There are no MCAT<sup>&reg;</sup> General Chemistry 2 classes currently scheduled. If you would like Lenox Hill Premedical to host a class near your location, please email Philip Murray at pmurray@lenoxhillpremedical.com or contact us at 203-524-1189.</small></p>
					<?php } else {$classCounter = 0;} ?>
						<br/><p>In this 3-hour lesson, you will learn the MCAT<sup>&reg;</sup>-relevant content for the middle third of introductory, college-level general chemistry. Topics include thermodynamics, kinetics, rate laws, equilibrium, Le Chatelier's principle, the chemistry of solutions, and the colligative properties. You will learn these chemistry topics at the same level of depth tested on the MCAT<sup>&reg;</sup>, and your instructor will teach you the most common ways they present themselves on the test.</p><br/>
					<h4 class="text-center">LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>general_chemistry_2_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>general_chemistry_2_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>general_chemistry_2_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>general_chemistry_2_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-success mcat-menu" data-toggle="modal" data-target="#genchem3">GENERAL CHEMISTRY 3</button>
	<div class="modal fade" id="genchem3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> GENERAL CHEMISTRY 3<br/>Acids and Bases, Redox, Electrochemistry</h4>
				</div>
				<div class="modal-body">
					<?php foreach ($classes as $class) {
						if ($class['Topic'] == 'genchem3') {$classCounter++; ?>
							<div class="row" style="border-bottom:1px solid lightgray; padding:10px;">
								<div class="col-sm-2" style="border-right:1px solid lightgray;">
									<div class="text-primary"><big><strong><?php echo strtoupper($class['Start']->format('M')); ?></strong></big><br/><?php echo $class['Start']->format('d, Y'); ?></div>
								</div>
								<div class="col-sm-10">
									<small><strong>Instructor:</strong> <?php echo $class['Instructor']; ?></span></small><br/>
									<small class="text-muted"><?php echo $class['Start']->format('g:ia').' - '.$class['End']->format('g:ia').' '.$class['Location']; ?></small><br/>
									<?php if ($class['AvailableSeats'] > 0) { ?>
										<small class="text-danger"><?php echo $class['AvailableSeats']; ?> tickets available</small><br/>
										<small style="color:green"><strong><?php echo ($class['Price'] == 0) ? 'FREE' : '$'.$class['Price'].'.00'; ?></strong></small> <a href="/class-registration?classId=<?php echo $class['ClassId']; ?>" class="btn btn-xs btn-success" style="color:white; text-decoration:none">Reserve Seat</a></span>
									<?php } else {?>
										<small class="text-danger">Class full<br/>No tickets available</small>
									<?php } ?>
								</div>
							</div>
					<?php }} if ($classCounter == 0) { ?>
						<p class="text-danger"><small>There are no MCAT<sup>&reg;</sup> General Chemistry 3 classes currently scheduled. If you would like Lenox Hill Premedical to host a class near your location, please email Philip Murray at pmurray@lenoxhillpremedical.com or contact us at 203-524-1189.</small></p>
					<?php } else {$classCounter = 0;} ?>
						<br/><p>In this 3-hour lesson, you will learn the MCAT<sup>&reg;</sup>-relevant content for the last third of introductory, college-level general chemistry. The topics are acid-base chemistry and electrochemistry, including equilibrium expressions, titrations, buffers, indicators, galvanic and electrolytic cells, concentration cells, and the relationship between electrochemistry and thermodynamics. You will learn these chemistry topics at the same level of depth tested on the MCAT<sup>&reg;</sup>, and your instructor will teach you the most common ways they will present themselves on the test.</p><br/>
					<h4 class="text-center">LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>general_chemistry_3_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>general_chemistry_3_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>general_chemistry_3_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>general_chemistry_3_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-success mcat-menu" data-toggle="modal" data-target="#orgo1">ORGANIC CHEMISRTY</button>
	<div class="modal fade" id="orgo1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> ORGANIC CHEMISTRY<br/>Stereochemistry, Substitution Reactions, Spectroscopy, Alkanes, Alcohols, and Carbonyls</h4>
				</div>
				<div class="modal-body">
					<?php foreach ($classes as $class) {
						if ($class['Topic'] == 'organicchem') {$classCounter++; ?>
							<div class="row" style="border-bottom:1px solid lightgray; padding:10px;">
								<div class="col-sm-2" style="border-right:1px solid lightgray;">
									<div class="text-primary"><big><strong><?php echo strtoupper($class['Start']->format('M')); ?></strong></big><br/><?php echo $class['Start']->format('d, Y'); ?></div>
								</div>
								<div class="col-sm-10">
									<small><strong>Instructor:</strong> <?php echo $class['Instructor']; ?></span></small><br/>
									<small class="text-muted"><?php echo $class['Start']->format('g:ia').' - '.$class['End']->format('g:ia').' '.$class['Location']; ?></small><br/>
									<?php if ($class['AvailableSeats'] > 0) { ?>
										<small class="text-danger"><?php echo $class['AvailableSeats']; ?> tickets available</small><br/>
										<small style="color:green"><strong><?php echo ($class['Price'] == 0) ? 'FREE' : '$'.$class['Price'].'.00'; ?></strong></small> <a href="/class-registration?classId=<?php echo $class['ClassId']; ?>" class="btn btn-xs btn-success" style="color:white; text-decoration:none">Reserve Seat</a></span>
									<?php } else {?>
										<small class="text-danger">Class full<br/>No tickets available</small>
									<?php } ?>
								</div>
							</div>
					<?php }} if ($classCounter == 0) { ?>
						<p class="text-danger"><small>There are no MCAT<sup>&reg;</sup> Organic Chemistry classes currently scheduled. If you would like Lenox Hill Premedical to host a class near your location, please email Philip Murray at pmurray@lenoxhillpremedical.com or contact us at 203-524-1189.</small></p>
					<?php } else {$classCounter = 0;} ?>
						<br/><p>In this 3-hour lesson, you will learn the MCAT<sup>&reg;</sup>-relevant content of introductory, college-level organic chemistry. The topics include nomenclature, functional groups, stereochemistry, SN1/SN2 reactions, purification and separation, spectroscopy, the physical and chemical properties of hydrocarbons, alcohols, carbonyl compounds, and nitrogen-containing compounds. You will learn these chemistry topics at the same level of depth tested on the MCAT<sup>&reg;</sup>, and your instructor will teach you the most common ways they will present themselves on the test.</p><br/>
					<h4 class="text-center">LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>organic_chemistry_1_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>organic_chemistry_1_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>organic_chemistry_1_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>organic_chemistry_1_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-success mcat-menu" data-toggle="modal" data-target="#biochem1">BIOCHEMISTRY 1</button>
	<div class="modal fade" id="biochem1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> BIOCHEMISTRY 1<br/>Carbohydrates, Lipids, Proteins, Enzyme Chemistry, and Cellular Respiration</h4>
				</div>
				<div class="modal-body">
					<?php foreach ($classes as $class) {
						if ($class['Topic'] == 'biochem1') {$classCounter++; ?>
							<div class="row" style="border-bottom:1px solid lightgray; padding:10px;">
								<div class="col-sm-2" style="border-right:1px solid lightgray;">
									<div class="text-primary"><big><strong><?php echo strtoupper($class['Start']->format('M')); ?></strong></big><br/><?php echo $class['Start']->format('d, Y'); ?></div>
								</div>
								<div class="col-sm-10">
									<small><strong>Instructor:</strong> <?php echo $class['Instructor']; ?></span></small><br/>
									<small class="text-muted"><?php echo $class['Start']->format('g:ia').' - '.$class['End']->format('g:ia').' '.$class['Location']; ?></small><br/>
									<?php if ($class['AvailableSeats'] > 0) { ?>
										<small class="text-danger"><?php echo $class['AvailableSeats']; ?> tickets available</small><br/>
										<small style="color:green"><strong><?php echo ($class['Price'] == 0) ? 'FREE' : '$'.$class['Price'].'.00'; ?></strong></small> <a href="/class-registration?classId=<?php echo $class['ClassId']; ?>" class="btn btn-xs btn-success" style="color:white; text-decoration:none">Reserve Seat</a></span>
									<?php } else {?>
										<small class="text-danger">Class full<br/>No tickets available</small>
									<?php } ?>
								</div>
							</div>
					<?php }} if ($classCounter == 0) { ?>
						<p class="text-danger"><small>There are no MCAT<sup>&reg;</sup> Biochemistry 1 classes currently scheduled. If you would like Lenox Hill Premedical to host a class near your location, please email Philip Murray at pmurray@lenoxhillpremedical.com or contact us at 203-524-1189.</small></p>
					<?php } else {$classCounter = 0;} ?>
						<br/><p>In this 3-hour lesson, you will learn the MCAT<sup>&reg;</sup>-relevant content for the first half of college-level biochemistry. The topics include the structure and function of carbohydrates, lipids, and proteins, enzyme kinetics, cellular respiration, and metabolism. You will learn these biochemistry topics at the same level of depth tested on the MCAT<sup>&reg;</sup>, and your instructor will teach you the most common ways they will present themselves on the test.</p><br/>
					<h4 class="text-center">LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biochemistry_1_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biochemistry_1_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biochemistry_1_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biochemistry_1_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-success mcat-menu" data-toggle="modal" data-target="#biochem2">BIOCHEMISTRY 2</button>
	<div class="modal fade" id="biochem2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> BIOCHEMISTRY 2<br/>Molecular and Mendelian Genetics</h4>
				</div>
				<div class="modal-body">
					<?php foreach ($classes as $class) {
						if ($class['Topic'] == 'biochem2') {$classCounter++; ?>
							<div class="row" style="border-bottom:1px solid lightgray; padding:10px;">
								<div class="col-sm-2" style="border-right:1px solid lightgray;">
									<div class="text-primary"><big><strong><?php echo strtoupper($class['Start']->format('M')); ?></strong></big><br/><?php echo $class['Start']->format('d, Y'); ?></div>
								</div>
								<div class="col-sm-10">
									<small><strong>Instructor:</strong> <?php echo $class['Instructor']; ?></span></small><br/>
									<small class="text-muted"><?php echo $class['Start']->format('g:ia').' - '.$class['End']->format('g:ia').' '.$class['Location']; ?></small><br/>
									<?php if ($class['AvailableSeats'] > 0) { ?>
										<small class="text-danger"><?php echo $class['AvailableSeats']; ?> tickets available</small><br/>
										<small style="color:green"><strong><?php echo ($class['Price'] == 0) ? 'FREE' : '$'.$class['Price'].'.00'; ?></strong></small> <a href="/class-registration?classId=<?php echo $class['ClassId']; ?>" class="btn btn-xs btn-success" style="color:white; text-decoration:none">Reserve Seat</a></span>
									<?php } else {?>
										<small class="text-danger">Class full<br/>No tickets available</small>
									<?php } ?>
								</div>
							</div>
					<?php }} if ($classCounter == 0) { ?>
						<p class="text-danger"><small>There are no MCAT<sup>&reg;</sup> Biochemistry 2 classes currently scheduled. If you would like Lenox Hill Premedical to host a class near your location, please email Philip Murray at pmurray@lenoxhillpremedical.com or contact us at 203-524-1189.</small></p>
					<?php } else {$classCounter = 0;} ?>
						<br/><p>In this 3-hour lesson, you will learn the MCAT<sup>&reg;</sup>-relevant content for the second half of college-level biochemistry. The topics include DNA structure and replication, transcription, translation, genetic mutations, evolutionary genetics, and Hardy-Weinberg equilibrium. You will learn these biochemistry topics at the same level of depth tested on the MCAT<sup>&reg;</sup>, and your instructor will teach you the most common ways they will present themselves on the test.</p><br/>
					<h4 class="text-center">LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biochemistry_2_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biochemistry_2_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biochemistry_2_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biochemistry_2_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-success mcat-menu" data-toggle="modal" data-target="#biology1">BIOLOGY 1</button>
	<div class="modal fade" id="biology1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> BIOLOGY 1<br/>Cell Biology, Virology, Blood, and Immunobiology</h4>
				</div>
				<div class="modal-body">
					<?php foreach ($classes as $class) {
						if ($class['Topic'] == 'biology1') {$classCounter++; ?>
							<div class="row" style="border-bottom:1px solid lightgray; padding:10px;">
								<div class="col-sm-2" style="border-right:1px solid lightgray;">
									<div class="text-primary"><big><strong><?php echo strtoupper($class['Start']->format('M')); ?></strong></big><br/><?php echo $class['Start']->format('d, Y'); ?></div>
								</div>
								<div class="col-sm-10">
									<small><strong>Instructor:</strong> <?php echo $class['Instructor']; ?></span></small><br/>
									<small class="text-muted"><?php echo $class['Start']->format('g:ia').' - '.$class['End']->format('g:ia').' '.$class['Location']; ?></small><br/>
									<?php if ($class['AvailableSeats'] > 0) { ?>
										<small class="text-danger"><?php echo $class['AvailableSeats']; ?> tickets available</small><br/>
										<small style="color:green"><strong><?php echo ($class['Price'] == 0) ? 'FREE' : '$'.$class['Price'].'.00'; ?></strong></small> <a href="/class-registration?classId=<?php echo $class['ClassId']; ?>" class="btn btn-xs btn-success" style="color:white; text-decoration:none">Reserve Seat</a></span>
									<?php } else {?>
										<small class="text-danger">Class full<br/>No tickets available</small>
									<?php } ?>
								</div>
							</div>
					<?php }} if ($classCounter == 0) { ?>
						<p class="text-danger"><small>There are no MCAT<sup>&reg;</sup> Biology 1 classes currently scheduled. If you would like Lenox Hill Premedical to host a class near your location, please email Philip Murray at pmurray@lenoxhillpremedical.com or contact us at 203-524-1189.</small></p>
					<?php } else {$classCounter = 0;} ?>
						<br/><p>In this 3-hour lesson, you will learn the MCAT<sup>&reg;</sup>-relevant content for the first third of introductory, college-level biology. The topics include eukaryotic and prokaryotic cells, viruses, fungi, blood composition, blood types, blood clotting, and the immune system. You will learn these biology topics at the same level of depth tested on the MCAT<sup>&reg;</sup>, and your instructor will teach you the most common ways they will present themselves on the test.</p><br/>
					<h4 class="text-center">LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biology_1_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biology_1_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biology_1_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biology_1_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-success mcat-menu" data-toggle="modal" data-target="#biology2">BIOLOGY 2</button>
	<div class="modal fade" id="biology2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> BIOLOGY 2<br/>Physiology of the Cardiovascular, Respiratory, Digestive, and Renal Systems</h4>
				</div>
				<div class="modal-body">
					<?php foreach ($classes as $class) {
						if ($class['Topic'] == 'biology2') {$classCounter++; ?>
							<div class="row" style="border-bottom:1px solid lightgray; padding:10px;">
								<div class="col-sm-2" style="border-right:1px solid lightgray;">
									<div class="text-primary"><big><strong><?php echo strtoupper($class['Start']->format('M')); ?></strong></big><br/><?php echo $class['Start']->format('d, Y'); ?></div>
								</div>
								<div class="col-sm-10">
									<small><strong>Instructor:</strong> <?php echo $class['Instructor']; ?></span></small><br/>
									<small class="text-muted"><?php echo $class['Start']->format('g:ia').' - '.$class['End']->format('g:ia').' '.$class['Location']; ?></small><br/>
									<?php if ($class['AvailableSeats'] > 0) { ?>
										<small class="text-danger"><?php echo $class['AvailableSeats']; ?> tickets available</small><br/>
										<small style="color:green"><strong><?php echo ($class['Price'] == 0) ? 'FREE' : '$'.$class['Price'].'.00'; ?></strong></small> <a href="/class-registration?classId=<?php echo $class['ClassId']; ?>" class="btn btn-xs btn-success" style="color:white; text-decoration:none">Reserve Seat</a></span>
									<?php } else {?>
										<small class="text-danger">Class full<br/>No tickets available</small>
									<?php } ?>
								</div>
							</div>
					<?php }} if ($classCounter == 0) { ?>
						<p class="text-danger"><small>There are no MCAT<sup>&reg;</sup> Biology 2 classes currently scheduled. If you would like Lenox Hill Premedical to host a class near your location, please email Philip Murray at pmurray@lenoxhillpremedical.com or contact us at 203-524-1189.</small></p>
					<?php } else {$classCounter = 0;} ?>
						<br/><p>In this 3-hour lesson, you will learn the MCAT<sup>&reg;</sup>-relevant content for the middle third of introductory, college-level biology. The topics include anatomy and physiology of the heart, lungs, vasculature, digestive system, renal system, and excretory system. You will learn these biology topics at the same level of depth tested on the MCAT<sup>&reg;</sup>, and your instructor will teach you the most common ways they will present themselves on the test.</p><br/>
					<h4 class="text-center">LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biology_2_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biology_2_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biology_2_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biology_2_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-success mcat-menu" data-toggle="modal" data-target="#biology3">BIOLOGY 3</button>
	<div class="modal fade" id="biology3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> BIOLOGY 3<br/>Physiology of the Nervous, Musculoskeletal, Endocrine, and Reproductive Systems</h4>
				</div>
				<div class="modal-body">
					<?php foreach ($classes as $class) {
						if ($class['Topic'] == 'biology3') {$classCounter++; ?>
							<div class="row" style="border-bottom:1px solid lightgray; padding:10px;">
								<div class="col-sm-2" style="border-right:1px solid lightgray;">
									<div class="text-primary"><big><strong><?php echo strtoupper($class['Start']->format('M')); ?></strong></big><br/><?php echo $class['Start']->format('d, Y'); ?></div>
								</div>
								<div class="col-sm-10">
									<small><strong>Instructor:</strong> <?php echo $class['Instructor']; ?></span></small><br/>
									<small class="text-muted"><?php echo $class['Start']->format('g:ia').' - '.$class['End']->format('g:ia').' '.$class['Location']; ?></small><br/>
									<?php if ($class['AvailableSeats'] > 0) { ?>
										<small class="text-danger"><?php echo $class['AvailableSeats']; ?> tickets available</small><br/>
										<small style="color:green"><strong><?php echo ($class['Price'] == 0) ? 'FREE' : '$'.$class['Price'].'.00'; ?></strong></small> <a href="/class-registration?classId=<?php echo $class['ClassId']; ?>" class="btn btn-xs btn-success" style="color:white; text-decoration:none">Reserve Seat</a></span>
									<?php } else {?>
										<small class="text-danger">Class full<br/>No tickets available</small>
									<?php } ?>
								</div>
							</div>
					<?php }} if ($classCounter == 0) { ?>
						<p class="text-danger"><small>There are no MCAT<sup>&reg;</sup> Biology 3 classes currently scheduled. If you would like Lenox Hill Premedical to host a class near your location, please email Philip Murray at pmurray@lenoxhillpremedical.com or contact us at 203-524-1189.</small></p>
					<?php } else {$classCounter = 0;} ?>
						<br/><p>In this 3-hour lesson, you will learn the MCAT<sup>&reg;</sup>-relevant content for the final third of introductory, college-level biology. The topics include neurology, musculoskeletal physiology, endocrinology, and human development. You will learn these biology topics at the same level of depth tested on the MCAT<sup>&reg;</sup>, and your instructor will teach you the most common ways the topics will present themselves on the test.</p><br/>
					<h4 class="text-center">LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biology_3_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biology_3_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biology_3_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biology_3_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-success mcat-menu" data-toggle="modal" data-target="#crit1">CRITICAL ANALYSIS</button>
	<div class="modal fade" id="crit1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> CRITICAL ANALYSIS AND REASONING<br/>Approaches to Passages</h4>
				</div>
				<div class="modal-body">
					<?php foreach ($classes as $class) {
						if ($class['Topic'] == 'cars') {$classCounter++; ?>
							<div class="row" style="border-bottom:1px solid lightgray; padding:10px;">
								<div class="col-sm-2" style="border-right:1px solid lightgray;">
									<div class="text-primary"><big><strong><?php echo strtoupper($class['Start']->format('M')); ?></strong></big><br/><?php echo $class['Start']->format('d, Y'); ?></div>
								</div>
								<div class="col-sm-10">
									<small><strong>Instructor:</strong> <?php echo $class['Instructor']; ?></span></small><br/>
									<small class="text-muted"><?php echo $class['Start']->format('g:ia').' - '.$class['End']->format('g:ia').' '.$class['Location']; ?></small><br/>
									<?php if ($class['AvailableSeats'] > 0) { ?>
										<small class="text-danger"><?php echo $class['AvailableSeats']; ?> tickets available</small><br/>
										<small style="color:green"><strong><?php echo ($class['Price'] == 0) ? 'FREE' : '$'.$class['Price'].'.00'; ?></strong></small> <a href="/class-registration?classId=<?php echo $class['ClassId']; ?>" class="btn btn-xs btn-success" style="color:white; text-decoration:none">Reserve Seat</a></span>
									<?php } else {?>
										<small class="text-danger">Class full<br/>No tickets available</small>
									<?php } ?>
								</div>
							</div>
					<?php }} if ($classCounter == 0) { ?>
						<p class="text-danger"><small>There are no MCAT<sup>&reg;</sup> Critical Analysis and Reasoning Skills classes currently scheduled. If you would like Lenox Hill Premedical to host a class near your location, please email Philip Murray at pmurray@lenoxhillpremedical.com or contact us at 203-524-1189.</small></p>
					<?php } else {$classCounter = 0;} ?>
						<br/><p>In this lesson, you will cover the layout, scoring methods, and strategic approaches to the Critical Analysis and Reasoning Skills (CARS) section of the MCAT<sup>&reg;</sup>. You will then practice numerous MCAT<sup>&reg;</sup>-style CARS passages followed by a lesson on the two main approaches to correctly answering critical analysis questions.</p><br/>
					<h4 class="text-center">LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>critical_analysis_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>critical_analysis_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>critical_analysis_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>critical_analysis_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-success mcat-menu" data-toggle="modal" data-target="#psych1">PSYCHOLOGY 1</button>
	<div class="modal fade" id="psych1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> PSYCHOLOGY 1<br/>Sensing, Perceiving, and Responding to the Environment</h4>
				</div>
				<div class="modal-body">
					<?php foreach ($classes as $class) {
						if ($class['Topic'] == 'psychology1') {$classCounter++; ?>
							<div class="row" style="border-bottom:1px solid lightgray; padding:10px;">
								<div class="col-sm-2" style="border-right:1px solid lightgray;">
									<div class="text-primary"><big><strong><?php echo strtoupper($class['Start']->format('M')); ?></strong></big><br/><?php echo $class['Start']->format('d, Y'); ?></div>
								</div>
								<div class="col-sm-10">
									<small><strong>Instructor:</strong> <?php echo $class['Instructor']; ?></span></small><br/>
									<small class="text-muted"><?php echo $class['Start']->format('g:ia').' - '.$class['End']->format('g:ia').' '.$class['Location']; ?></small><br/>
									<?php if ($class['AvailableSeats'] > 0) { ?>
										<small class="text-danger"><?php echo $class['AvailableSeats']; ?> tickets available</small><br/>
										<small style="color:green"><strong><?php echo ($class['Price'] == 0) ? 'FREE' : '$'.$class['Price'].'.00'; ?></strong></small> <a href="/class-registration?classId=<?php echo $class['ClassId']; ?>" class="btn btn-xs btn-success" style="color:white; text-decoration:none">Reserve Seat</a></span>
									<?php } else {?>
										<small class="text-danger">Class full<br/>No tickets available</small>
									<?php } ?>
								</div>
							</div>
					<?php }} if ($classCounter == 0) { ?>
						<p class="text-danger"><small>There are no MCAT<sup>&reg;</sup> Psychology 1 classes currently scheduled. If you would like Lenox Hill Premedical to host a class near your location, please email Philip Murray at pmurray@lenoxhillpremedical.com or contact us at 203-524-1189.</small></p>
					<?php } else {$classCounter = 0;} ?>
						<br/><p>In this 3-hour lesson, you will learn the MCAT<sup>&reg;</sup>-relevant content for the first half of introductory, college-level psychology. The topics include sensory processing, perception, attention, cognition, consciousness, memory, language, emotion, and stress. You will learn these psychology topics at the same level of depth tested on the MCAT<sup>&reg;</sup>, and your instructor will teach you the most common ways the topics will present themselves on the test.</p><br/>
					<h4 class="text-center">LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>psychology_1_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>psychology_1_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>psychology_1_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>psychology_1_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-success mcat-menu" data-toggle="modal" data-target="#psych2">PSYCHOLOGY 2</button>
	<div class="modal fade" id="psych2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> PSYCHOLOGY 2<br/>Personality, Attitude, and Behavior</h4>
				</div>
				<div class="modal-body">
					<?php foreach ($classes as $class) {
						if ($class['Topic'] == 'psychology2') {$classCounter++; ?>
							<div class="row" style="border-bottom:1px solid lightgray; padding:10px;">
								<div class="col-sm-2" style="border-right:1px solid lightgray;">
									<div class="text-primary"><big><strong><?php echo strtoupper($class['Start']->format('M')); ?></strong></big><br/><?php echo $class['Start']->format('d, Y'); ?></div>
								</div>
								<div class="col-sm-10">
									<small><strong>Instructor:</strong> <?php echo $class['Instructor']; ?></span></small><br/>
									<small class="text-muted"><?php echo $class['Start']->format('g:ia').' - '.$class['End']->format('g:ia').' '.$class['Location']; ?></small><br/>
									<?php if ($class['AvailableSeats'] > 0) { ?>
										<small class="text-danger"><?php echo $class['AvailableSeats']; ?> tickets available</small><br/>
										<small style="color:green"><strong><?php echo ($class['Price'] == 0) ? 'FREE' : '$'.$class['Price'].'.00'; ?></strong></small> <a href="/class-registration?classId=<?php echo $class['ClassId']; ?>" class="btn btn-xs btn-success" style="color:white; text-decoration:none">Reserve Seat</a></span>
									<?php } else {?>
										<small class="text-danger">Class full<br/>No tickets available</small>
									<?php } ?>
								</div>
							</div>
					<?php }} if ($classCounter == 0) { ?>
						<p class="text-danger"><small>There are no MCAT<sup>&reg;</sup> Psychology 2 classes currently scheduled. If you would like Lenox Hill Premedical to host a class near your location, please email Philip Murray at pmurray@lenoxhillpremedical.com or contact us at 203-524-1189.</small></p>
					<?php } else {$classCounter = 0;} ?>
						<br/><p>In this 3-hour lesson, you will learn the MCAT<sup>&reg;</sup>-relevant content for the second half of introductory, college-level psychology. The topics include the biological basis of behavior, developmental stages, personality, psychological disorders, attitude, social factors that influence behavior, and the various theories of learning. You will learn these psychology topics at the same level of depth tested on the MCAT<sup>&reg;</sup>, and your instructor will teach you the most common ways these topics will present themselves on the test.</p><br/>
					<h4 class="text-center">LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>psychology_2_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>psychology_2_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>psychology_2_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>psychology_2_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-success mcat-menu" data-toggle="modal" data-target="#soc1">SOCIOLOGY</button>
	<div class="modal fade" id="soc1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> SOCIOLOGY<br/>Self-Identity, Social Interactions, and Demographics</h4>
				</div>
				<div class="modal-body">
					<?php foreach ($classes as $class) {
						if ($class['Topic'] == 'sociology') {$classCounter++; ?>
							<div class="row" style="border-bottom:1px solid lightgray; padding:10px;">
								<div class="col-sm-2" style="border-right:1px solid lightgray;">
									<div class="text-primary"><big><strong><?php echo strtoupper($class['Start']->format('M')); ?></strong></big><br/><?php echo $class['Start']->format('d, Y'); ?></div>
								</div>
								<div class="col-sm-10">
									<small><strong>Instructor:</strong> <?php echo $class['Instructor']; ?></span></small><br/>
									<small class="text-muted"><?php echo $class['Start']->format('g:ia').' - '.$class['End']->format('g:ia').' '.$class['Location']; ?></small><br/>
									<?php if ($class['AvailableSeats'] > 0) { ?>
										<small class="text-danger"><?php echo $class['AvailableSeats']; ?> tickets available</small><br/>
										<small style="color:green"><strong><?php echo ($class['Price'] == 0) ? 'FREE' : '$'.$class['Price'].'.00'; ?></strong></small> <a href="/class-registration?classId=<?php echo $class['ClassId']; ?>" class="btn btn-xs btn-success" style="color:white; text-decoration:none">Reserve Seat</a></span>
									<?php } else {?>
										<small class="text-danger">Class full<br/>No tickets available</small>
									<?php } ?>
								</div>
							</div>
					<?php }} if ($classCounter == 0) { ?>
						<p class="text-danger"><small>There are no MCAT<sup>&reg;</sup> Sociology classes currently scheduled. If you would like Lenox Hill Premedical to host a class near your location, please email Philip Murray at pmurray@lenoxhillpremedical.com or contact us at 203-524-1189.</small></p>
					<?php } else {$classCounter = 0;} ?>
						<br/><p>In this 3-hour lesson, you will learn the MCAT<sup>&reg;</sup>-relevant content for introductory, college-level sociology. The topics include self-concept, social identity, theories of social interactions, social institutions, demographics, and the effect of social stratification on health and well being. You will learn these sociology topics at the same level of depth tested on the MCAT<sup>&reg;</sup>, and your instructor will teach you the most common ways they will present themselves on the test.</p><br/>
					<h4 class="text-center">LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>sociology_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>sociology_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>sociology_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>sociology_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<br/><br/>
 </div>
 <div class="col-sm-6">
	<h4>&Agrave; LA CARTE MCAT<sup>&reg;</sup> CLASSES</h4>
	<p>
    Lenox Hill Premedical offers 3 seminars and 15 content lessons covering the full breadth of topics tested on the MCAT<sup>&reg;</sup>, taught by professional MCAT<sup>&reg;</sup> instructors on location at Connecticut's colleges and universities.</p>
	<p>Tickets for these classes can be reserved &agrave; la carte from the content lesson menu, just like a movie ticket.</p><br/>
	<h4>Why &agrave; la carte?</h4>
	<p>Because the &agrave; la carte model is ideally suited for the MCAT<sup>&reg;</sup>. First, the MCAT<sup>&reg;</sup> is uniquely challenging; it requires vast amounts of science knowledge and is considerably more difficult than any other graduate-level entrance examination. Second, premedical students are uniquely motivated; by the time they begin preparing for the MCAT<sup>&reg;</sup>, most premedical students already possess a great deal of academic self-awareness. They already know which science subjects and topics they need to work on and which ones they do not. &Agrave; la carte lessons are the most efficient and cost-effective way of learning the MCAT<sup>&reg;</sup>-relevant science content.</p>
 </div>
</div>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
