<?php $bucket = getenv('LHP_SITE_BUCKET'); ?>
<div class="row">
 <div class="col-sm-6">
	<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="10000">
	   <div class="carousel-inner">
	      <div class="item active">
	          <img style="margin:auto;" class="img-rounded img-thumbnail img-responsive" src="public/images/mhm_our_story_2.jpg">
	            <div class="carousel-caption">
	               <h2>
	                 <small style="color:white"></small>
	               </h2>
	            </div>
	      </div>
	      <div class="item">
	         <img style="margin:auto;" class="img-rounded img-thumbnail img-responsive" src="public/images/mcat_tutoring_1.jpg">
	            <div class="carousel-caption">
	              <h3>
	                 <small style="color:white"></small>
	              </h3>
	         </div>
	      </div>
	      <div class="item">
	            <img style="margin:auto;" class="img-rounded img-thumbnail img-responsive"src="public/images/mcat_tutoring_3.jpg">
	              <div class="carousel-caption">
	                <h3>
	                  <small style="color:white"></small>
	                </h3>
	            </div>
	      </div>
	   </div>
	</div><br/><br/><br/>
	<div class="text-center text-info"><h4>CONTENT LESSONS</h4></div>
	<button class="btn btn-info btn-sm mcat-menu" data-toggle="modal" data-target="#practice">PRACTICE SESSION</button>
	<div class="modal fade" id="practice" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> PRACTICE SESSION</h4>
				</div>
				<div class="modal-body">
					<p>Practice sessions involve sitting down with your Lenox Hill Premedical MCAT<sup>&reg;</sup> tutor and practicing MCAT<sup>&reg;</sup> passages and question sets that <i>neither</i> of you have seen before.</p>
					<p>Similar to a medical resident working with an attending physician on a new patient's case, practice sessions allow you to work side by side with an MCAT<sup>&reg;</sup> expert on a new MCAT<sup>&reg;</sup> passage of a chosen topic. By doing this, you will get a first-hand experience of how your MCAT<sup>&reg;</sup> tutor:
					</p>
					<img style="float:right" class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>mcat_practice_session_snippet_1.jpg">
					<ol>
					 <li>Analyzes the passage.</li>
					 <li>Diagnoses the questions.</li>
					 <li>Manages timing.</li>
					 <li>Handles unfamiliar content.</li>
					 <li>Arrives at an answer choice.</li>
					</ol><br/>
					<p>Equally important, but less obvious, is how practice sessions with a Lenox Hill Premedical MCAT<sup>&reg;</sup> tutor allow you to <i>calibrate</i> your skill level by comparing yourself to your tutor. As you get deeper and deeper into your MCAT<sup>&reg;</sup> studying, you will begin to ask yourself questions like:</p>
					<img style="float:right;" class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>mcat_practice_session_snippet_2.jpg">
					<ul><li>"Is my acid/base chemistry knowledge good enough?"</li>
						<li>"Do I need to review the thin lens equation?"</li>
						<li>"Should I memorize the DSM-5 mental disorders?"</li>
						<li>"Am I prepared for a tough question on the structure of lipids?"</li>
					</ul>
					<br/>
					<p>Practicing a few passages with your MCAT<sup>&reg;</sup> tutor on a topic that is concerning you will allow you to quickly ascertain where you stand on that topic. For example, if you are outperforming your tutor on optics passages, and your tutor scored a 131 on the Chem/Phys section, then you can rest assured that you need not study any more optics! With this information comes piece of mind that your MCAT<sup>&reg;</sup> studying is on the right track.</p>
					<p>Once you have established a solid core of MCAT<sup>&reg;</sup> content knowledge, you will find that a practice session with your MCAT<sup>&reg;</sup> tutor is the <i>single most effective</i> method of preparing for your MCAT<sup>&reg;</sup>. Approximately half of all scheduled Lenox Hill Premedical tutoring sessions are practice sessions.</p>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-info btn-sm mcat-menu" data-toggle="modal" data-target="#physics1">PHYSICS 1</button>
	<div class="modal fade" id="physics1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> PHYSICS 1<br/> Kinematics, Forces, Energy, and Simple Harmonic Motion</h4>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<img src="<?php echo $bucket; ?>physics_1_cover_sheet.gif">
					</div>
					<p>In this lesson, you will cover the details of the laws of motion, Newton's laws of forces, the relationship between work and energy, torque, and simple harmonic motion, including the most common ways these concepts present themselves on the MCAT<sup>&reg;</sup>.
					</p><br/>
					<h4>LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>physics_1_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>physics_1_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>physics_1_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>physics_1_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-info btn-sm mcat-menu" data-toggle="modal" data-target="#physics2">PHYSICS 2</button>
	<div class="modal fade" id="physics2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> PHYSICS 2<br/>Nuclear Physics, Fluids, Solids, and Wave Mechanics</h4>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<img src="<?php echo $bucket; ?>physics_2_cover_sheet.gif">
					</div>
					<p>In this lesson, you will cover the details of radioactive decay, fluid dynamics, properties of solids, and the fundamentals of mechanical waves, including the most common way these topics present themselves on the MCAT<sup>&reg;</sup>.</p><br/>
					<h4>LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>physics_2_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>physics_2_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>physics_2_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>physics_2_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-info btn-sm mcat-menu" data-toggle="modal" data-target="#physics3">PHYSICS 3</button>
	<div class="modal fade" id="physics3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> PHYSICS 3<br/>Electricity, Magnetism, Circuits, and Optics</h4>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<img src="<?php echo $bucket; ?>physics_3_cover_sheet.gif">
					</div>
					<p>In this lesson, you will cover the details of electrostatics, magnetism, the right hand rule, DC/AC circuits, and the fundamentals of light and optics, specifying the different ways these topics are tested on the MCAT<sup>&reg;</sup>.</p><br/>
					<h4>LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>physics_3_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>physics_3_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>physics_3_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>physics_3_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-info btn-sm mcat-menu" data-toggle="modal" data-target="#genchem1">GENERAL CHEMISTRY 1</button>
	<div class="modal fade" id="genchem1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> GENERAL CHEMISTRY 1<br/>Periodic Trends, Quantum Mechanics, and Gases</h4>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<img src="<?php echo $bucket; ?>general_chemistry_1_cover_sheet.gif">
					</div>
					<p>In this lesson, you will cover the details of atomic structure, periodicity, quantum mechanics, and the kinetic molecular theory of gases, including the most common ways these topics present themselves on the MCAT<sup>&reg;</sup>.</p><br/>
					<h4>LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>general_chemistry_1_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>general_chemistry_1_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>general_chemistry_1_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>general_chemistry_1_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-info btn-sm mcat-menu" data-toggle="modal" data-target="#genchem2">GENERAL CHEMISTRY 2</button>
	<div class="modal fade" id="genchem2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> GENERAL CHEMISTRY 2<br/>Thermodynamics, Solutions, and Colligative Properties</h4>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<img src="<?php echo $bucket; ?>general_chemistry_2_cover_sheet.gif">
					</div>
					<p>In this lesson, you will study the details of thermodynamics, kinetics, rate laws, equilibrium, Le Chatelier's principle, the chemistry of solutions, and the colligative properties, including the most common way these topics present themselves on the MCAT<sup>&reg;</sup>.</p><br/>
					<h4>LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>general_chemistry_2_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>general_chemistry_2_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>general_chemistry_2_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>general_chemistry_2_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-info btn-sm mcat-menu" data-toggle="modal" data-target="#genchem3">GENERAL CHEMISTRY 3</button>
	<div class="modal fade" id="genchem3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> GENERAL CHEMISTRY 3<br/>Acids and Bases, Redox, Electrochemistry</h4>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<img src="<?php echo $bucket; ?>general_chemistry_3_cover_sheet.gif">
					</div>
					<p>In this lesson, you will cover the details of acid-base chemistry and electrochemistry, including equilibrium expressions, titrations, buffers, indicators, galvanic cells, electrolytic cells, concentration cells, and the relationship between electrochemistry and thermodynamics, including the ways these topics will present themselves on the MCAT<sup>&reg;</sup>.</p><br/>
					<h4>LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>general_chemistry_3_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>general_chemistry_3_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>general_chemistry_3_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>general_chemistry_3_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-info btn-sm mcat-menu" data-toggle="modal" data-target="#orgo1">ORGANIC CHEMISRTY 1</button>
	<div class="modal fade" id="orgo1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> ORGANIC CHEMISTRY 1<br/>Nomenclature, Stereochemistry, Substitution Reactions, and Spectroscopy</h4>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<img src="<?php echo $bucket; ?>organic_chemistry_1_cover_sheet.gif">
					</div>
					<p>In this lesson, you will cover the details of nomenclature, functional groups, stereochemistry, SN1 reactions, SN2 reactions, purification, separation, and spectroscopy, including the most common ways these topics present themselves on the MCAT<sup>&reg;</sup>.</p><br/>
					<h4>LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>organic_chemistry_1_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>organic_chemistry_1_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>organic_chemistry_1_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>organic_chemistry_1_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-info btn-sm mcat-menu" data-toggle="modal" data-target="#orgo2">ORGANIC CHEMISRTY 2</button>
	<div class="modal fade" id="orgo2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> ORGANIC CHEMISTRY 2<br/>Alkanes, Alcohols, Carbonyls, and Nitrogen-Containing Compounds</h4>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<img src="<?php echo $bucket; ?>organic_chemistry_2_cover_sheet.gif">
					</div>
					<p>In this lesson, you will cover the details of the physical and chemical properties of hydrocarbons, alcohols, carbonyl compounds, and nitrogen-containing compounds, including their syntheses, and the most common reactions in which they appear on the MCAT<sup>&reg;</sup>.</p><br/>
					<h4>LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>organic_chemistry_2_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>organic_chemistry_2_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>organic_chemistry_2_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>organic_chemistry_2_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-info btn-sm mcat-menu" data-toggle="modal" data-target="#biochem1">BIOCHEMISTRY 1</button>
		<div class="modal fade" id="biochem1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> BIOCHEMISTRY 1<br/>Carbohydrates, Lipids, Proteins, Enzyme Chemistry, and Cellular Respiration</h4>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<img src="<?php echo $bucket; ?>biochemistry_1_cover_sheet.gif">
					</div>
					<p>In this lesson, you will cover the structure and function of three of the four major classes of biological molecules; carbohydrates, lipids, and proteins. You will then cover the details of enzyme kinetics and cellular metabolism including the most common ways these topics present themselves on the MCAT<sup>&reg;</sup>.</p><br/>
					<h4>LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biochemistry_1_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biochemistry_1_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biochemistry_1_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biochemistry_1_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-info btn-sm mcat-menu" data-toggle="modal" data-target="#biochem2">BIOCHEMISTRY 2</button>
		<div class="modal fade" id="biochem2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> BIOCHEMISTRY 2<br/>Molecular and Mendelian Genetics</h4>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<img src="<?php echo $bucket; ?>biochemistry_2_cover_sheet.gif">
					</div>
					<p>In this lesson, you will cover the details of DNA replication, transcription, translation, genetic mutations, pedigree analysis, and Hardy-Weinberg equilibrium, including the most common ways these topics present themselves on the MCAT<sup>&reg;</sup>.</p><br/>
					<h4>LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biochemistry_2_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biochemistry_2_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biochemistry_2_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biochemistry_2_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-info btn-sm mcat-menu" data-toggle="modal" data-target="#biology1">BIOLOGY 1</button>
		<div class="modal fade" id="biology1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> BIOLOGY 1<br/>Cell Biology, Virology, Blood, and Immunobiology</h4>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<img src="<?php echo $bucket; ?>biology_1_cover_sheet.gif">
					</div>
					<p>In this lesson, you will cover the details of eukaryotic and prokaryotic cells, viruses, fungi, blood composition, blood types, blood clotting, and the immune system as well as the most common ways these topics present themselves on the MCAT<sup>&reg;</sup>.</p><br/>
					<h4>LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biology_1_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biology_1_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biology_1_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biology_1_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-info btn-sm mcat-menu" data-toggle="modal" data-target="#biology2">BIOLOGY 2</button>
		<div class="modal fade" id="biology2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> BIOLOGY 2<br/>Physiology of the Cardiovascular, Respiratory, Digestive, and Renal Systems</h4>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<img src="<?php echo $bucket; ?>biology_2_cover_sheet.gif">
					</div>
					<p>In this lesson, you will cover the anatomy and physiology of the heart, lungs, vasculature, digestive system, and the renal portion of the excretory system, along with the most frequent ways these topics present themselves on the MCAT<sup>&reg;</sup>.</p><br/>
					<h4>LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biology_2_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biology_2_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biology_2_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biology_2_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-info btn-sm mcat-menu" data-toggle="modal" data-target="#biology3">BIOLOGY 3</button>
		<div class="modal fade" id="biology3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> BIOLOGY 3<br/>Physiology of the Nervous, Musculoskeletal, Endocrine, and Reproductive Systems</h4>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<img src="<?php echo $bucket; ?>biology_3_cover_sheet.gif">
					</div>
					<p>In this lesson, you will cover the neurology, musculoskeletal physiology, endocrinology, and the human development required for the MCAT<sup>&reg;</sup>, including the most common ways these topics present themselves on the MCAT<sup>&reg;</sup>.</p><br/>
					<h4>LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biology_3_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biology_3_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biology_3_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>biology_3_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-info btn-sm mcat-menu" data-toggle="modal" data-target="#crit1">CRITICAL ANALYSIS AND REASONING</button>
	<div class="modal fade" id="crit1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> CRITICAL ANALYSIS AND REASONING<br/>Approaches to Passages</h4>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<img src="<?php echo $bucket; ?>critical_analysis_cover_sheet.gif">
					</div>
					<p>In this lesson, you will cover the layout, scoring methods, and strategic approaches to the Critical Analysis and Reasoning section of the MCAT<sup>&reg;</sup>. You will then practice four MCAT<sup>&reg;</sup>-style critical analysis passages followed by a lesson on the two main approaches to correctly answering critical analysis questions.</p><br/>
					<h4>LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>critical_analysis_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>critical_analysis_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>critical_analysis_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>critical_analysis_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-info btn-sm mcat-menu" data-toggle="modal" data-target="#psych1">PSYCHOLOGY 1</button>
	<div class="modal fade" id="psych1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> PSYCHOLOGY 1<br/>Sensing, Perceiving, and Responding to the Environment</h4>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<img src="<?php echo $bucket; ?>psychology_1_cover_sheet.png">
					</div>
					<p>In this lesson, you will be introduced to MCAT<sup>&reg;</sup> psychology. You will then cover sensory processing, perception, attention, cognition, consciousness, memory, language, emotion, and stress, including the most common ways these topics present themselves on the MCAT<sup>&reg;</sup>.</p><br/>
					<h4>LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>psychology_1_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>psychology_1_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>psychology_1_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>psychology_1_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-info btn-sm mcat-menu" data-toggle="modal" data-target="#psych2">PSYCHOLOGY 2</button>
	<div class="modal fade" id="psych2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> PSYCHOLOGY 2<br/>Personality, Attitude, and Behavior</h4>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<img src="<?php echo $bucket; ?>psychology_2_cover_sheet.png">
					</div>
					<p>In this lesson, you will begin by studying the biological bases of behavior, including developmental stages. You will then cover personality, psychological disorders, attitude, social factors that influence behavior, and the various theories of learning, focusing on how these topics will appear on the MCAT<sup>&reg;</sup>.</p><br/>
					<h4>LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>psychology_2_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>psychology_2_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>psychology_2_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>psychology_2_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
	<button class="btn btn-info btn-sm mcat-menu" data-toggle="modal" data-target="#soc1">SOCIOLOGY</button>
	<div class="modal fade" id="soc1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center" id="myModalLabel">MCAT<sup>&reg;</sup> SOCIOLOGY<br/>Self-Identity, Social Interactions, and Demographics</h4>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<img src="<?php echo $bucket; ?>sociology_cover_sheet.png">
					</div>
					<p>In this lesson, you will learn the MCAT<sup>&reg;</sup>-relevant concepts in social psychology and sociology. You will cover self-concept, social identity, and theories of social interactions followed by social institutions, demographics, and the effect that social stratification has on health and well being.</p><br/>
					<h4>LESSON SNIPPETS</h4>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>sociology_snippet_1.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>sociology_snippet_2.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>sociology_snippet_3.png">
					</div>
					<hr>
					<div class="text-center">
						<img class="img-thumbnail img-rounded" src="<?php echo $bucket; ?>sociology_snippet_4.png">
					</div>
				</div>
			</div>
		</div>
	</div>
 </div>
 <div class="col-sm-6">
	<h3>&Agrave; LA CARTE TUTORING</h3>
	<p>
    Lenox Hill Premedical offers 17 content lessons covering the full breadth of topics tested on the MCAT<sup>&reg;</sup>. Sessions are conducted either online or at one of our office locations (Manhattan, Stamford, Boston). Sessions are scheduled &agrave; la carte (i.e. one at a time) from the content lesson menu by contacting your MCAT<sup>&reg;</sup> tutor directly.</p>
	<p>
	If you are new to Lenox Hill Premedical and would like to work with an MCAT<sup>&reg;</sup> tutor, please email Philip Murray at pmurray@lenoxhillpremedical.com or call us at (203) 524-1189.
	</p>
	<p>
	The fee for tutoring sessions is $125 per hour. Lenox Hill Premedical employs professional MCAT<sup>&reg;</sup> tutors who have scored in the top 10 percent on the actual MCAT<sup>&reg;</sup>, have three or more years of teaching experience, and who are patient and understanding.
	</p>
 </div>
 </div>
</div>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
