<div class="row">
   <div class="col-sm-6">
	 <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="10000">	        
	   <div class="carousel-inner">
	      <div class="item active">
	          <img class="img-rounded img-thumbnail img-responsive" src="public/images/mhm_our_story_1.jpg">
	            <div class="carousel-caption">
	               <h2>
	                 <small style="color:white"></small>
	               </h2>
	            </div>
	      </div>
	      <div class="item">
	         <img class="img-rounded img-thumbnail img-responsive" src="public/images/mcat_study_halls_1.jpg">
	            <div class="carousel-caption">
	              <h3>
	                 <small style="color:white"></small>
	              </h3>
	         </div>
	      </div>
	      <div class="item">
	            <img class="img-rounded img-thumbnail img-responsive"src="public/images/mhm_our_story_3.jpg">
	              <div class="carousel-caption">
	                <h3>
	                  <small style="color:white"></small>
	                </h3>
	            </div>
	      </div>
	   </div>
	 </div>
    </div>
	<div class="col-sm-6">
		<h3>OUR STORY</h3> 
		<p>Healthcare in the United States is changing rapidly, and medical schools are working to address a number of upcoming challenges:
		</p>
		 <ul>
		  <li>Physician shortages</li>
		  <li>The Affordable Care Act</li>
		  <li>Health and wellness education</li>
		 </ul>	
		<p>to name just a few.</p>
		<p>MCAT<sup>&reg;</sup> 2015 (the new MCAT<sup>&reg;</sup>) is at the forefront of these changes.</p>
		<p>Since the announcement of the new MCAT<sup>&reg;</sup> nearly five years ago, the Lenox Hill Premedical team,
            founded by a group of MCAT<sup>&reg;</sup> tutors working out of small office in the
		Lenox Hill section of Manhattan, has worked tirelessly to develop the MCAT<sup>&reg;</sup> content, web technologies, and
		 expertise required to prepare students for the new MCAT<sup>&reg;</sup>.</p>
		<p style="padding-bottom:80px"><i>Our mission is to help aspiring physicians achieve a score on the new MCAT<sup>&reg;</sup>
                that gains acceptance to medical school.</i>
        </p>
	</div>
</div>

<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>

