<?php $bucket = getenv('LHP_SITE_BUCKET'); ?>
<div class="row">
 <div class="col-sm-6 text-center">
	<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="10000">
	   <div class="carousel-inner">
	      <div class="item active">
	          <img style="margin:auto;" class="img-rounded img-thumbnail img-responsive" src="public/images/study_halls_2.jpg">
	            <div class="carousel-caption">
	               <h2><br/>
	                 <small style="color:white"></small>
	               </h2>
	            </div>
	      </div>
	      <div class="item">
	         <img style="margin:auto;" class="img-rounded img-thumbnail img-responsive" src="public/images/mhm_online_mcats_2.jpg">
	            <div class="carousel-caption">
	              <h3>
	                 <small style="color:white"></small>
	              </h3>
	         </div>
	      </div>
	      <div class="item">
	            <img style="margin:auto;" class="img-rounded img-thumbnail img-responsive"src="public/images/mhm_online_mcats_1.jpg">
	              <div class="carousel-caption">
	                <h3>
	                  <small style="color:white"></small>
	                </h3>
	            </div>
	      </div>
	   </div>
	</div>
	<div style="padding-top:15px;padding-bottom:15px;">
		<a href="user/login?beginFreeMcat=true" class="btn btn-lg btn-success">BEGIN FREE MCAT<sup>&reg;</sup></a>
	</div>
	<img class="img-rounded img-thumbnail" src="<?php echo $bucket; ?>practice_tests_snippet_1.png"><br/><br/>
	<img class="img-rounded img-thumbnail" src="<?php echo $bucket; ?>practice_tests_snippet_2.png"><br/><br/>
	<img class="img-rounded img-thumbnail" src="<?php echo $bucket; ?>practice_tests_snippet_3.png"><br/><br/>
	<img class="img-rounded img-thumbnail" src="<?php echo $bucket; ?>practice_tests_snippet_4.png"><br/><br/>
	<img class="img-rounded img-thumbnail" src="<?php echo $bucket; ?>practice_tests_snippet_5.png">
 </div>
 <div class="col-sm-6">
	<h4>FULL-LENGTH PRACTICE MCAT<sup>&reg;</sup>S</h4>
	<p>Lenox Hill Premedical offers 3 full-length practice tests that accurately reflect every aspect of the real MCAT<sup>&reg;</sup>. Practice tests include scaled scores and explanations for all correct and incorrect answer choices. We invite you take Full-length MCAT<sup>&reg;</sup> 1 courtesy of our team by clicking the green button.</p>
	<p>Additional practice tests can be purchased &agrave; la carte once you are logged in and can be repeated an unlimited number of times for 90 days.</p>
 </div>
</div>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
