<div id="header"><table id="header_table"><tbody><tr><td>
                <div id="paginator">
                    <?php if (isset($paginationArray)) {
                        echo 'Questions ' . $paginationArray['min'] . '-' . $paginationArray['max'] . ' of ' . $paginationArray['total'];
                    } ?>
                </div>
            </td><td>
                <div id="logo_for_full_length_header">
                    <a style="color:white" href="/user"><i>LENOX HILL PREMEDICAL</i></a>
                </div>
            </td><td>
                <div id="timer"></div>
            </td></tr></tbody></table>
</div>
<div style="position:fixed;top:50px;left:10%;width:80%;">
	<p style="text-align:center">Click on the question you want to review<br/><br/>Key:<br/>
		<img src="/public/images/marked_question.png"> Marked Question &nbsp;&nbsp;&nbsp;
		<img src="/public/images/completed_question.png"> Completed Question &nbsp;&nbsp;&nbsp;
		<img src="/public/images/incomplete_question.png"> Incomplete Question
	</p>
</div>
<div id="review_table">
	<table>
		<thead>
			<tr><th>Questions</th><th>Marked</th><th>Incomplete</th><th>Completed</th></tr>
		</thead>
		<tbody>
			<?php foreach ($reviewObject as $array) {
				$url_string = '/full-length/content-page/';
				$url_string .= $examId.'/';
				$url_string .= $fullLengthNumber.'/';
				$url_string .= $array['PageNumber'];
				$url_string .= '?q='.$array['ItemNumber'];
				echo '<tr><td>';
				echo '<a href="'.$url_string.'">';
				if ($array['Mark'] == 1) {
					echo '<img src="/public/images/marked_question.png">';
				} elseif ($array['SubmittedAnswer'] == NULL) {
					echo '<img src="/public/images/incomplete_question.png">';
				} else {
					echo '<img src="/public/images/completed_question.png">';
				}
				echo 'Question '.$array['OffsetItemNumber'].'</a></td><td>';
				echo ($array['Mark'] == 1) ? 'Yes' : '&nbsp';
				echo '</td><td>';
				echo ($array['SubmittedAnswer'] == NULL) ? 'Yes' : '&nbsp';
				echo '</td><td>';
				echo ($array['SubmittedAnswer'] !== NULL) ? 'Yes' : '&nbsp';
				echo '</td></tr>';
			} ?>
		</tbody>
	</table>
</div>

<div id="footer">
    <form action="/full-length/review-page/<?php echo $examId.'/'.$fullLengthNumber.'/'.$pageNumber; ?>" method="post">
    <table id="footer_table">
        <tbody>
        <tr>
            <td style="width:20%">
                <div id="footer_left">
                    <input id="previousButton" class="mcat_submit_button" type="submit" name="previous" value="PREVIOUS">
                </div>
            </td>
            <td style="width:60%">
                <div id="footer_center">
                    <?php if ($hasMarkedQuestions) { ?>
                        <input class="mcat_submit_button" type="submit" name="reviewMarked" value="REVIEW MARKED">
                    <?php } ?>
                    <?php if ($hasIncompleteQuestions) { ?>
                        <input class="mcat_submit_button" style="width:160px" type="submit" name="reviewIncomplete" value="REVIEW INCOMPLETE">
                    <?php } ?>
                    <input class="mcat_submit_button" type="submit" name="reviewAll" value="REVIEW ALL">
                    <input type="hidden" name="timeRemaining" value="<?php echo $timeRemaining; ?>">
                </div>
            </td>
            <td style="width:20%">
                <div id="footer_right">
                    <input class="mcat_submit_button" type="submit" name="endSection" value="END SECTION">
                </div>
            </td>
        </tr>
        </tbody>
    </table></form>
</div>
