<div id="header"><table id="header_table"><tbody><tr><td>
                <div id="paginator">
                    <?php if (isset($paginationArray)) {
                        echo 'Questions ' . $paginationArray['min'] . '-' . $paginationArray['max'] . ' of ' . $paginationArray['total'];
                    } ?>
                </div>
            </td><td>
                <div id="logo_for_full_length_header">
                    <a style="color:white" href="/user"><i>LENOX HILL PREMEDICAL</i></a>
                </div>
            </td><td>
                <div class="mcat_header_links">
                    <a style="color:white;<?php if ($section == 'phys') {echo 'font-weight:bold';} ?>" href="/full-length/review-directions-page/<?php echo $examId.'/'.$fullLengthNumber.'/'.$firstPagesOfSections['phys']; ?>">Chem/Phys</a>&nbsp;&nbsp;
                    <a style="color:white;<?php if ($section == 'crit') {echo 'font-weight:bold';} ?>" href="/full-length/review-directions-page/<?php echo $examId.'/'.$fullLengthNumber.'/'.$firstPagesOfSections['crit']; ?>">Crit Analysis</a>&nbsp;&nbsp;
                    <a style="color:white;<?php if ($section == 'bio') {echo 'font-weight:bold';} ?>" href="/full-length/review-directions-page/<?php echo $examId.'/'.$fullLengthNumber.'/'.$firstPagesOfSections['bio']; ?>">Bio/Biochem</a>&nbsp;&nbsp;
                    <a style="color:white;<?php if ($section == 'psy') {echo 'font-weight:bold';} ?>" href="/full-length/review-directions-page/<?php echo $examId.'/'.$fullLengthNumber.'/'.$firstPagesOfSections['psy']; ?>">Psych/Soc</a>&nbsp;&nbsp;
                </div>
            </td></tr></tbody></table>
</div>
<div id="non-content">
    <div id="review_table">
        <table>
            <thead>
            <tr><th>Questions</th><th>Marked</th><th>Incomplete</th><th>Completed</th></tr>
            </thead>
            <tbody>
            <?php foreach ($reviewObject as $array) {
                $url_string = '/full-length/review-content-page/';
                $url_string .= $examId.'/';
                $url_string .= $fullLengthNumber.'/';
                $url_string .= $array['PageNumber'];
				$url_string .= '?q='.$array['ItemNumber'];
                echo '<tr><td>';
                echo '<a href="'.$url_string.'">';
                echo 'Question '.$array['OffsetItemNumber'];
                echo ($array['Correct'] == 'Correct') ? '<span style="color:green"> - Correct</span>' : '<span style="color:red"> - Incorrect</span>';
                echo '</a></td><td>';
                echo ($array['Mark'] == 1) ? 'Yes' : '&nbsp';
                echo '</td><td>';
                echo ($array['SubmittedAnswer'] == NULL) ? 'Yes' : '&nbsp';
                echo '</td><td>';
                echo ($array['SubmittedAnswer'] !== NULL) ? 'Yes' : '&nbsp';
                echo '</td></tr>';
            } ?>
            </tbody>
        </table>
    </div>
</div>

<div id="footer">
    <table id="footer_table">
        <tbody>
        <tr>
            <td>
                <div id="footer_left">
                    <form action="/full-length/review-review-page/<?php echo $examId.'/'.$fullLengthNumber.'/'.$pageNumber; ?>" method="post">
                    <input class="mcat_submit_button" type="submit" name="previous" value="PREVIOUS">
                </div>
            </td>
            <td>
                <div id="footer_center">
                    <input class="mcat_submit_button" type="submit" name="reviewAll" value="REVIEW ALL">
                </div>
            </td>
            <td>
                <div id="footer_right">
                    <input class="mcat_submit_button" type="submit" name="endSection" value="END SECTION">
                    </form>
                </div>
            </td>
        </tr>
        </tbody>
    </table></form>
</div>
