<div class="row">
 <div class="col-sm-6">
	<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="10000">	        
	   <div class="carousel-inner">
	      <div class="item active">
	          <img class="img-rounded img-thumbnail img-responsive" src="public/images/mhm_simulated_mcats_1.jpg">
	            <div class="carousel-caption">
	               <h2><br/>
	                 <small style="color:white"></small>
	               </h2>
	            </div>
	      </div>
	      <div class="item">
	         <img class="img-rounded img-thumbnail img-responsive" src="public/images/mhm_simulated_mcats_2.jpg">
	            <div class="carousel-caption">
	              <h3>
	                 <small style="color:white"></small>
	              </h3>
	         </div>
	      </div>
	      <div class="item">
	            <img class="img-rounded img-thumbnail img-responsive" src="public/images/mhm_simulated_mcats_3.jpg">
	              <div class="carousel-caption">
	                <h3>
	                  <small style="color:white">Lenox Hill, New York City</small>
	                </h3>
	            </div>
	      </div>
	   </div>  
	</div>
 </div>
 <div class="col-sm-6">
     <p class="text-danger">Note: Currently, our simulated MCAT<sup>&reg;</sup> 2015 exams are in beta testing.
         If you would like to take a simulated MCAT<sup>&reg;</sup> as part of a beta testing group, please contact your MCAT<sup>&reg;</sup> instructor
         or contact our scheduling coordinator by clicking <a href="make-an-appointment">here</a>. Beta testing MCAT<sup>&reg;</sup> administrations
         are offered at half-price (terms and conditions apply).
     </p><br/>

     <h3>SIMULATED MCAT<sup>&reg;</sup> EXAMS</h3>
     <p><span style="color:green; border:1px solid green; padding:2px">&nbsp;Price: $399/administration &nbsp;</span></p>
  <p>Simulated MCAT<sup>&reg;</sup> exams are administered at our Manhattan office or on-location at university campuses
      throughout the northeast. They are designed to precisely mimic the complete test-day experience.
      Exams begin at 9:00 AM and last approximately 8 hours.
  </p>
  <p>To schedule a simulated MCAT<sup>&reg;</sup>, click <a href="make-an-appointment">here.</a></p><br/>
  <h4>SCORE REPORTS</h4>
  <p>After completing your simulated MCAT, you will receive a comprehensive score report, with detailed explanations and pathologies (why the wrong answers are wrong).</p>
  <br/>
  <h4>SCALED SCORES</h4> 
   <p>Included in your score report will be your scaled score (118-132 on each section). Our scaling algorithms have been researched and developed
    to produce raw-to-scaled score conversions that mimic those used on the actual MCAT<sup>&reg;</sup>.</p>
   <br/>
 </div>
</div>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
