<div class="row">
    <div class="col-sm-6">
        <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="10000">
            <div class="carousel-inner">
                <div class="item active">
                    <img class="img-rounded img-thumbnail img-responsive" src="public/images/mcat_tutoring_1.jpg">
                </div>
                <div class="item">
                    <img class="img-rounded img-thumbnail img-responsive" src="public/images/study_halls_3.jpg">
                </div>
                <div class="item">
                    <img class="img-rounded img-thumbnail img-responsive" src="public/images/mhm_our_story_2.jpg">
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <h4>SPONSORSHIP</h4>
        <p>Lenox Hill Premedical invests in Connecticut's serious premedical students by sponsoring their MCAT<sup>&reg;</sup> preparation - providing them with MCAT<sup>&reg;</sup> resources and professional instruction while simultaneously promoting the Lenox Hill Premedical brand on Connecticut's college and university campuses. Sponsored students enjoy:</p>
        <ol>
            <li>Free access to all of Lenox Hill Premedical's MCAT<sup>&reg;</sup> preparation material until they are accepted to medical school.</li>
            <li>The abilty to attend any Lenox Hill Premedical MCAT<sup>&reg;</sup> class at no charge.</li>
			<li>Complementary advising and counseling from Lenox Hill Premedical's MCAT<sup>&reg;</sup> instructors and advising physicians.</li>
            <li>Monetary compensation if a sale is made using a sponsored student's promotional code (students may opt out of this if receiving payments affects their financial aid).</li>
        </ol><br/>
		<p>If you attend school in Connecticut, are dedicated to becoming a physician, and are interested in being sponsored by Lenox Hill Premedical, or if you would like to recommend your child, student, classmate, or colleague for sponsorship, please contact Philip Murray at pmurray@lenoxhillpremedical.com or call us at 203-524-1189 to schedule an interview.</p>
    </div>
</div>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
