<div class="row">
    <div class="col-sm-6">
        <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="10000">
            <div class="carousel-inner">
                <div class="item active">
                    <img class="img-rounded img-thumbnail img-responsive" src="public/images/study_halls_1.jpg">
                </div>
                <div class="item">
                    <img class="img-rounded img-thumbnail img-responsive" src="public/images/study_halls_2.jpg">
                </div>
                <div class="item">
                    <img class="img-rounded img-thumbnail img-responsive" src="public/images/study_halls_3.jpg">
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <h4>WHAT IS AN MCAT<sup>&reg;</sup> STUDY HALL?</h4>
        <p>It's simple.</p>
        <ol>
            <li>We email you with a time and location where we will be studying (e.g Starbucks, Barnes and Noble, library etc.).</li>
            <li>You come by and study at the same location for as long or as little as you want.</li>
            <li>That's it!</li>
        </ol><br/>
        <h4>WHY IT WORKS?</h4>
        <p>Because it keeps us motivated, which will ultimately lead to a higher MCAT<sup>&reg;</sup> score.</p><br/>
        <h4>IS IT A STUDY GROUP?</h4>
        <p>No. We study on our own, but in the same location. However, you are welcome to ask the Lenox Hill Premedical Instructor any questions.
        </p><br/>
        <h4>ARE THERE ANY FEES?</h4>
        <p>No. Your presence and motivation is all that is required.</p>
        <br/>
        <h4>HOW TO SIGN UP?</h4>
        <p>It's easy! Just email our scheduling coordinator, Nicole, at nicolew@lenoxhillpremedical.com and tell us you
        would like to be on our study hall list.
        </p>
    </div>
</div>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
