<?php if ($beginFreeMcat) { ?>
<form action="/user/login" method="post" class="form-horizontal">
	<div class="form-group">
		<h4 class="col-sm-offset-2 col-sm-10 text-success">
			Please choose one of the following options:
		</h4>
	</div>
		<input name="email" type="hidden" class="form-control" autofocus="autofocus" placeholder="Email" value="student@lenoxhillpremedical.com">
		<input name="credential" type="hidden" class="form-control" placeholder="Password" value="student">
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-success"><strong>1. </strong></span><a href="/user/register" class="btn btn-success" style="text-decoration:none; color:white;">CREATE AN ACCOUNT</a>
			<span class="text-success">(Your free practice MCAT<sup>&reg;</sup> will be saved for future use, and only you will have access)</span><br/><br/>
			<span class="text-success"><strong>2. </strong></span><button type="submit" name="submit" class="btn btn-success" value="">TAKE MCAT<sup>&reg;</sup> ANONYMOUSLY</button>
			<span class="text-success">(Your free practice MCAT<sup>&reg;</sup> may not be saved for future use, and other students will have access)</span>
		</div>
	</div>
</form>
<?php } else {?>
<form action="/user/login" method="post" class="form-horizontal">
    <div class="form-group">
        <p class="col-sm-offset-2 col-sm-6 text-danger"><?php if (isset($message)) {echo $message;} ?></p>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label" for="identity">Email</label>
        <div class="col-sm-6">
            <input name="email" type="text" class="form-control" autofocus="autofocus" placeholder="Email" value="">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label" for="identity">Password</label>
        <div class="col-sm-6">
            <input name="credential" type="password" class="form-control" placeholder="Password" value="">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" name="submit" class="btn btn-default" value="">Sign In</button>
        </div>
    </div>
    <div class="col-sm-offset-2 col-sm-10">
        <p>Forgot your password? Click <a href="/user/forgot-password">here.</a></p>
    </div>
</form>
<?php } ?>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
