<h3>Change Password for <?php echo $email; ?></h3>
<form action="/user/reset-password?token=<?php echo $token; ?>" method="post" class="form-horizontal">
    <div class="form-group">
        <ul class="col-sm-offset-2 col-sm-6 text-danger"><?php if (isset($flash['message'])) {echo '<li>'.$flash['message'].'</li>';} ?></ul>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label" for="newCredential">New Password</label>
        <div class="col-sm-6">
            <input name="newCredential" class="form-control" placeholder="Password" type="password" value="">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label" for="newCredentialVerify">Verify New Password</label>
        <div class="col-sm-6">
            <input name="newCredentialVerify" class="form-control" placeholder="Password" type="password" value="">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" name="submit" class="btn btn-default" value="">Submit</button>
        </div>
    </div>
</form>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>