<!DOCTYPE html>
<html lang="en" style="margin:0;width:100%;height:100%">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Lenox Hill Premedical</title>
	<link rel="icon" type="image/png" href="/public/images/favicon-16x16.png" sizes="16x16">
    <!-- Bootstrap -->
    <link href="/public/css/bootstrap.css" rel="stylesheet">
    <style type="text/css" media="screen">
        .carousel .item {-webkit-transition: opacity 3s;
            -moz-transition: opacity 3s; -ms-transition: opacity 3s;
            -o-transition: opacity 3s; transition: opacity 3s;}
        .carousel .active.left {left:0;opacity:0;z-index:2;}
        .carousel .active.right {right:0;opacity:0;z-index:2;}
        .carousel .next {left:0;opacity:1;z-index:1;}
		.mcat-menu {display:block; width:200px; margin-left:auto; margin-right:auto; margin-top:8px;}
    </style>
</head>
<body style="margin:0;width:100%;height:100%;background:linear-gradient(#FFFFFF,#CCCCFF);background-repeat:no-repeat;background-attachment:fixed">
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand text-center" href="/" style="padding-top:10px;">
                <span class="text-canter text-primary"><i>Lenox Hill</i></span>
                <br/>
                <span class="text-primary small"><i><sup>Premedical&nbsp;&nbsp;</sup></i></span>
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
				<li><a href="/mcat-classes">Classes</a></li>
                <li><a href="/user">My MCAT<sup>&reg;</sup> Exams</a></li>
                <li><a href="/contact-us">Contact Us</a></li>
                <?php if (isset($_SESSION['role']) && $_SESSION['role'] == 'admin') {?>
                    <li><a href="/admin">Admin</a></li>
                <?php } ?>
                <?php if (isset($_SESSION['role']) && ($_SESSION['role'] == 'writer' || $_SESSION['role'] == 'admin')) { ?>
                    <li><a href="/writer">Writer</a></li>
                 <?php } ?>
                <li><a href="/user/logout">Sign Out</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="container">
    <?php echo $content; ?>
</div>
<div class="navbar navbar-default navbar-fixed-bottom text-center" style="min-height:30px; max-height:40px;">
<div class="container-fluid" style="padding:5px; font-size:0.8em;">
	<span class="text-muted text-center small">
		MCAT<sup>&reg;</sup> is a Registered Trademark of the Association of American Medical Colleges (AAMC).
		The AAMC is the <i>sole</i> authority on the MCAT<sup>&reg;</sup>. The AAMC does not endorse any of the content created by
		Lenox Hill Premedical. Copyright &#169 <?php echo date('Y'); ?> by Lenox Hill Premedical LLC.
	</span>
</div>
</div>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="/public/js/jquery.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/public/js/bootstrap.js"></script>
</body>
</html>