<form action="/user/forgot-password" method="post" class="form-horizontal">
    <div class="form-group">
        <ul class="col-sm-offset-2 col-sm-6 text-danger"><?php if (isset($flash['message'])) {echo '<li>'.$flash['message'].'</li>';} ?></ul>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label" for="email">Email</label>
        <div class="col-sm-6">
            <input name="email" class="form-control" placeholder="Email" type="text" value="">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" name="submit" class="btn btn-default" value="">Request New Password</button>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <p> <a href="/user/login">Back to login</a></p>
        </div>
    </div>
</form
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>