<script type="text/javascript">
    $(".alert").alert();
    function buildDeleteWarning(id) {
        var newDiv = $("<div class='alert alert-danger'/>"),
            cancelButton = $("<button type='button' class='btn close' data-dismiss='alert' aria-hidden='true'>Cancel</button>"),
            deleteMcatTag = $("<a>").attr("href", "/user/delete-exam?examId=" + id),
            message = $("<p>This will permanently and irretrievably delete all information about this particular MCAT (Exam ID: "+id+"). Are you sure you would like to do this?</p>");
        deleteMcatTag.append("<button class='btn btn-danger'>DELETE EXAM</button>");
        newDiv.append(cancelButton).append(message).append(deleteMcatTag);
        $("#mcat_message").append(newDiv);
    }
</script>
<?php if ($anonymousStudent) { //User is anonymous premed student ?>
<div style="padding:10px" class="text-danger"><strong>REMINDER:</strong> These practice MCATs can be accessed and modified by other Lenox Hill Premedical students. If you would like your own free practice test, sign out of this account and create a Lenox Hill Premedical account using your own login credentials (click <a href="/user/logout" class="text-danger"><strong>here</strong></a> to sign out).<br/><br/></div>
<?php } elseif ($priceInCents < 5000) { ?>
<span class="text-success">Promo code approved!</span>
<?php } else { ?>
<h4>Welcome <?php echo $firstName; ?></h4>
<?php } ?>
<div id="mcat_message"></div>
<div class="text-info"><?php echo $flash['message']; ?></div>
<div class="panel-group" id="accordion">
    <div class="panel panel-default">
        <div class="panel-heading">
			<h4 class="panel-title">
                <?php if ($expDates[1] > $now) {?>
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                        <span class="text-info">Full-Length MCAT<sup>&reg;</sup> 1 </span>
                    </a><small class="text-info">- Active until <?php echo $expDates[1]->format('F jS\, Y \a\t g:ia'); ?></small>&nbsp;
                    <a href="/user/provision-exam?fullLengthNumber=1" style="color:white" class="btn btn-success btn-xs">New Exam</a>
                    <a href="/user/provision-exam?fullLengthNumber=1&studyMode" style="color:white" class="btn btn-success btn-xs">Study Mode</a>
                <?php } else {?>
                    <form action="/user" method="post" name="stripecheckoutform1" id="stripecheckoutform1">
                        <span style="line-height:32px" class="text-info">Full-Length MCAT<sup>&reg;</sup> 1<small> - Click to purchase 90-Day Access &nbsp;</small></span>
                        <input type="hidden" name="fullLengthNumber" value="1">
						<input type="hidden" name="promoCode" value="<?php echo $promoCode; ?>">
                        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                data-name="Lenox Hill Premedical"
                                data-image="public/images/apple-touch-icon-144x144.png"
                                data-key="<?php echo $stripePublishableKey; ?>"
                                data-amount="<?php echo $priceInCents; ?>"
                                data-description="Full-Length MCAT 1"
                                data-label="$<?php echo ($priceInCents/100); ?>.00"
                                data-allowRememberMe="false">
                        </script>
                    </form>
                <?php }; ?>
			</h4>
        </div>
	<?php if ($expDates[1] > $now) { ?>
        <div id="collapseOne" class="panel-collapse collapse<?php echo ($currentFullLength == 1) ? ' in' : '';?>">
            <div class="panel-body">
                <table class="table table-condensed">
                    <thead>
                    <tr>
                        <th>MCAT<sup>&reg;</sup> Exam</th>
                        <th>Status:</th>
                        <th>Action:</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($exams as $exam) {?>
                        <?php if ($exam['FullLengthNumber'] == 1) { ?>
                            <tr>
                                <td class="small"><span class="text-muted"><?php echo $exam['ExamId']; ?>:Created on <?php echo $exam['DateCreated']; ?> (ET)</span></td>
                                <?php if ($exam['Status'] == 'incomplete') {?>
                                    <td>Incomplete</td>
                                    <td><a href="<?php echo '/full-length/'.$exam['PageType'].'-page/'.$exam['ExamId'].'/'.$exam['FullLengthNumber'].'/'.$exam['CurrentPageNumber']; ?>" class="btn btn-primary btn-xs">Resume</a>
                                        <button id="<?php echo $exam['ExamId'];?>" class="btn btn-danger btn-xs" onclick="buildDeleteWarning(this.id)">Delete</button>
                                    </td>
                                <?php } else {; ?>
                                    <td class="small">
                                        Chem:<span class="text-success"><strong><?php echo ($exam['PhysScore'] == NULL ? 'NA' : $exam['PhysScore']); ?></strong></span>&nbsp;
                                        Crit:<span class="text-success"><strong><?php echo ($exam['CritScore'] == NULL ? 'NA' : $exam['CritScore']); ?></strong></span>&nbsp;
                                        Bio:<span class="text-success"><strong><?php echo ($exam['BioScore'] == NULL ? 'NA' : $exam['BioScore']); ?></strong></span>&nbsp;
                                        Psych:<span class="text-success"><strong><?php echo ($exam['PsyScore'] == NULL ? 'NA' : $exam['PsyScore']); ?></strong></span>&nbsp;
                                    </td>
                                    <td><a href="<?php echo '/full-length/review-'.$exam['PageType'].'-page/'.$exam['ExamId'].'/1/'.$exam['CurrentPageNumber']; ?>" class="btn btn-xs btn-info">Review</a>
                                        <button id="<?php echo $exam['ExamId'];?>" class="btn btn-danger btn-xs" onclick="buildDeleteWarning(this.id)">Delete</button>
                                    </td>
                                <?php }; ?>
                            </tr>
                        <?php }; ?>
                    <?php }; ?>
                    </tbody>
                </table>
            </div>
        </div>
	<?php } ?>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <?php if (($expDates[2] > $now)) {?> 
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">       
					<span class="text-info">Full-Length MCAT<sup>&reg;</sup> 2 </span>
                    </a><small class="text-info">- Active until <?php echo $expDates[2]->format('F jS\, Y \a\t g:ia'); ?></small>&nbsp;
                    <a href="/user/provision-exam?fullLengthNumber=2" style="color:white" class="btn btn-success btn-xs">New Exam</a>
					<a href="/user/provision-exam?fullLengthNumber=2&studyMode" style="color:white" class="btn btn-success btn-xs">Study Mode</a>
                <?php } else {?>
                    <form action="/user" method="post" name="stripecheckoutform2" id="stripecheckoutform2">
					    <span style="line-height:32px" class="text-info">Full-Length MCAT<sup>&reg;</sup> 2<small> - Click to purchase 90-Day Access &nbsp;</small></span>
                        <input type="hidden" name="fullLengthNumber" value="2">
						<input type="hidden" name="promoCode" value="<?php echo $promoCode; ?>">
                        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                data-name="Lenox Hill Premedical"
                                data-image="public/images/apple-touch-icon-144x144.png"
                                data-key="<?php echo $stripePublishableKey; ?>"
                                data-amount="<?php echo $priceInCents; ?>"
                                data-description="Full-Length MCAT 2"
                                data-label="$<?php echo ($priceInCents/100); ?>.00"
								data-allowRememberMe="false">
                        </script>
                    </form>
                <?php }; ?>
            </h4>
        </div>
	<?php if ($expDates[2] > $now) { ?>
        <div id="collapseTwo" class="panel-collapse collapse<?php echo ($currentFullLength == 2) ? ' in' : '';?>">
            <div class="panel-body">
                <table class="table table-condensed">
                    <thead>
                    <tr>
                        <th>MCAT<sup>&reg;</sup> Exam</th>
                        <th>Status:</th>
                        <th>Action:</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($exams as $exam) {?>
                        <?php if ($exam['FullLengthNumber'] == 2) { ?>
                            <tr>
                                <td class="small"><span class="text-muted"><?php echo $exam['ExamId']; ?>:Created on <?php echo $exam['DateCreated']; ?> (ET)</span></td>
                                <?php if ($exam['Status'] == 'incomplete') {?>
                                    <td>Incomplete</td>
                                    <td><a href="<?php echo '/full-length/'.$exam['PageType'].'-page/'.$exam['ExamId'].'/'.$exam['FullLengthNumber'].'/'.$exam['CurrentPageNumber']; ?>" class="btn btn-primary btn-xs">Resume</a>
                                        <button id="<?php echo $exam['ExamId'];?>" class="btn btn-danger btn-xs" onclick="buildDeleteWarning(this.id)">Delete</button>
                                    </td>
                                <?php } else {; ?>
                                    <td class="small">
                                        Chem:<span class="text-success"><strong><?php echo ($exam['PhysScore'] == NULL ? 'NA' : $exam['PhysScore']); ?></strong></span>&nbsp;
                                        Crit:<span class="text-success"><strong><?php echo ($exam['CritScore'] == NULL ? 'NA' : $exam['CritScore']); ?></strong></span>&nbsp;
                                        Bio:<span class="text-success"><strong><?php echo ($exam['BioScore'] == NULL ? 'NA' : $exam['BioScore']); ?></strong></span>&nbsp;
                                        Psych:<span class="text-success"><strong><?php echo ($exam['PsyScore'] == NULL ? 'NA' : $exam['PsyScore']); ?></strong></span>&nbsp;
                                    </td>
                                    <td><a href="<?php echo '/full-length/review-'.$exam['PageType'].'-page/'.$exam['ExamId'].'/2/'.$exam['CurrentPageNumber']; ?>" class="btn btn-xs btn-info">Review</a>
                                        <button id="<?php echo $exam['ExamId'];?>" class="btn btn-danger btn-xs" onclick="buildDeleteWarning(this.id)">Delete</button>
                                    </td>
                                <?php }; ?>
                            </tr>
                        <?php }; ?>
                    <?php }; ?>
                    </tbody>
                </table>
            </div>
        </div>
	<?php } ?>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <?php if ($expDates[3] > $now) {?>
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                        <span class="text-info">Full-Length MCAT<sup>&reg;</sup> 3 </span>
                    </a><small class="text-info">- Active until <?php echo $expDates[3]->format('F jS\, Y \a\t g:ia'); ?></small>&nbsp;
                    <a href="/user/provision-exam?fullLengthNumber=3" style="color:white" class="btn btn-success btn-xs">New Exam</a>
					<a href="/user/provision-exam?fullLengthNumber=3&studyMode" style="color:white" class="btn btn-success btn-xs">Study Mode</a>	
                <?php } else {?>
                    <form action="/user" method="post" name="stripecheckoutform3" id="stripecheckoutform3">
	                    <span style="line-height:32px" class="text-info">Full-Length MCAT<sup>&reg;</sup> 3<small> - Click to purchase 90-Day Access &nbsp;</small></span>
                        <input type="hidden" name="fullLengthNumber" value="3">
						<input type="hidden" name="promoCode" value="<?php echo $promoCode; ?>">
                        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                data-name="Lenox Hill Premedical"
                                data-image="public/images/apple-touch-icon-144x144.png"
                                data-key="<?php echo $stripePublishableKey; ?>"
                                data-amount="<?php echo $priceInCents; ?>"
                                data-description="Full-Length MCAT 3"
                                data-label="$<?php echo ($priceInCents/100); ?>.00"
								data-allowRememberMe="false">
                        </script>
                    </form>
                <?php }; ?>
            </h4>
        </div>
	<?php if ($expDates[3] > $now) { ?>
        <div id="collapseThree" class="panel-collapse collapse<?php echo ($currentFullLength == 3) ? ' in' : '';?>">
            <div class="panel-body">
                <table class="table table-condensed">
                    <thead>
                    <tr>
                        <th>MCAT<sup>&reg;</sup> Exam</th>
                        <th>Status:</th>
                        <th>Action:</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($exams as $exam) {?>
                        <?php if ($exam['FullLengthNumber'] == 3) { ?>
                            <tr>
                                <td class="small"><span class="text-muted"><?php echo $exam['ExamId']; ?>:Created on <?php echo $exam['DateCreated']; ?> (ET)</span></td>
                                <?php if ($exam['Status'] == 'incomplete') {?>
                                    <td>Incomplete</td>
                                    <td><a href="<?php echo '/full-length/'.$exam['PageType'].'-page/'.$exam['ExamId'].'/'.$exam['FullLengthNumber'].'/'.$exam['CurrentPageNumber']; ?>" class="btn btn-primary btn-xs">Resume</a>
                                        <button id="<?php echo $exam['ExamId'];?>" class="btn btn-danger btn-xs" onclick="buildDeleteWarning(this.id)">Delete</button>
                                    </td>
                                <?php } else {; ?>
                                    <td class="small">
                                        Chem:<span class="text-success"><strong><?php echo ($exam['PhysScore'] == NULL ? 'NA' : $exam['PhysScore']); ?></strong></span>&nbsp;
                                        Crit:<span class="text-success"><strong><?php echo ($exam['CritScore'] == NULL ? 'NA' : $exam['CritScore']); ?></strong></span>&nbsp;
                                        Bio:<span class="text-success"><strong><?php echo ($exam['BioScore'] == NULL ? 'NA' : $exam['BioScore']); ?></strong></span>&nbsp;
                                        Psych:<span class="text-success"><strong><?php echo ($exam['PsyScore'] == NULL ? 'NA' : $exam['PsyScore']); ?></strong></span>&nbsp;
                                    </td>
                                    <td><a href="<?php echo '/full-length/review-'.$exam['PageType'].'-page/'.$exam['ExamId'].'/3/'.$exam['CurrentPageNumber']; ?>" class="btn btn-xs btn-info">Review</a>
                                        <button id="<?php echo $exam['ExamId'];?>" class="btn btn-danger btn-xs" onclick="buildDeleteWarning(this.id)">Delete</button>
                                    </td>
                                <?php }; ?>
                            </tr>
                        <?php }; ?>
                    <?php }; ?>
                    </tbody>
                </table>
            </div>
        </div>
	<?php } ?>
    </div>	 
</div>
<div class="text-info"><small>Have a promo code? Type it in:</small> 
	<form action="/user" method="get">
		<input type="text" name="promoCode">
		<input type="submit" value="GO">
	</form>
</div>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
