<div id="header"><table id="header_table"><tbody><tr><td>
                <div id="paginator">
                </div>
            </td><td>
                <div id="logo_for_full_length_header">
                    <a style="color:white" href="/user"><i>LENOX HILL PREMEDICAL</i></a>
                </div>
            </td><td>
                <div id="timer"></div>
            </td></tr></tbody></table>
</div>
<div class="tutorial_page">
	<p>You have completed your examinee agreement and the tutorial. Your practice MCAT will begin on the next screen.
		Good luck, and congratulations on your decision to pursue a career in medicine!</p>
	<p>- The Lenox Hill Premedical MCAT team.</p>
</div>
<div class="tutorial_page2">
	Click the "Begin Exam" button to begin your practice MCAT.
</div>
<div id="footer">
    <form action="/full-length/warning-page/<?php echo $examId.'/'.$fullLengthNumber.'/'.$pageNumber; ?>" method="post">
        <input class="mcat_submit_button" type="submit" name="yes" value="BEGIN EXAM">
        <input type="hidden" name="timeRemaining" value="<?php echo $timeRemaining; ?>">
    </form>
</div>