<!DOCTYPE html>
<html lang="en" style="margin:0;width:100%;height:100%">
<head>
    <title>Lenox Hill Premedical</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="/public/images/favicon-16x16.png" sizes="16x16">


    <!-- Bootstrap -->
    <link href="/public/css/bootstrap.css" rel="stylesheet">
</head>
<body style="margin:0;width:100%;height:100%;background:linear-gradient(#FFFFFF,#CCCCFF);background-repeat:no-repeat;background-attachment:fixed">
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand text-center" href="/user" style="padding-top:10px;">
                <span class="text-canter text-primary"><i>Lenox Hill</i></span>
                <br/>
                <span class="text-primary small"><i><sup>Premedical&nbsp;&nbsp;</sup></i></span>
            </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/writer/manage-passages">Manage Passages</a></li>
                <li><a href="/writer/manage-discretes">Manage Discretes</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="container">
    <?php echo $content; ?>
</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="/public/js/jquery.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/public/js/bootstrap.js"></script>
</body>
</html>