<script type="text/javascript">
    function toggleSolution(anchorTag) {
        var span = anchorTag.nextSibling.nextSibling.nextSibling;
        if (span.style.display == "none") {
            span.style.display = "inline";
        } else {
            span.style.display = "none";
        }
    }
</script>
<style>
    span.question_equation {
        display:block;
        text-align:center;
        margin-top:5px;
        margin-bottom:5px;
    }
	fieldset {
        margin-bottom:20px;
    }
	fieldset table {
		border-collapse: collapse; 
		border: solid thin;
		margin-left: auto;
		margin-right: auto;
		margin-top: 10px;
		margin-bottom: 10px;
	}
	fieldset thead {
		border: solid thin;
	}
	fieldset th {
		padding: 3px;
		border: solid thin;
	}
	fieldset td {
		padding: 3px;
	}
    .passage td {
        padding:3px;
        border: solid thin;
    }
    .mcat_answer_letter {
        float:left;
        padding-left:2px;
    }
    .mcat_solution_button {
        color:blue;
        margin-left:-13px;
        padding-left:1px;
        padding-right:1px;
        float:left;
        cursor:pointer;
        border:1px solid blue;
        border-radius:10px;
    }
    .mcat_answer_choice_container {
        margin-left:20px;
    }
    .mcat_distractor_container {
        color: red;
    }
    .mcat_explanation_container {
        color:blue;
    }
    .mcat_question_text img {
        display:block;
        margin-left:auto;
        margin-right:auto;
    }
    .mcat_label {
        padding:2px;
        margin-left:20px;
        min-height:30px;
    }
    legend {
        background-color:beige;
    }
    .mcat_question_text {
        margin-left:20px;
        margin-bottom:30px;
    }
</style>
<div class="text-danger"><?php echo $flash['message']; ?></div>
<nav>
    <ul class="pagination pagination-sm">
        <li class="previous <?php echo ($page == 1) ? 'disabled' : ''; ?>">
            <a href="/writer/manage-discretes?page=<?php echo ($page == 1) ? 1 : $page-1; ?>"><span aria-hidden="true">&larr;</span> Prev</a>
        </li>
        <?php for ($i=1;$i<=$lastPage;$i++) {?>
            <li <?php if ($page == $i) {?>class="active"<?php } ?>><a href="/writer/manage-discretes?page=<?php echo $i;?>"><?php echo $i; ?></a></li>
        <?php } ?>
        <li class="next <?php echo ($page == $lastPage) ? 'disabled' : ''; ?>">
            <a href="/writer/manage-discretes?page=<?php echo ($page == $lastPage) ? $lastPage : $page+1; ?>">Next <span aria-hidden="true">&rarr;</span></a>
        </li>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="/writer/create-discrete" class="btn btn-sm btn-success">New Question</a>
    </ul>
</nav>
<div class="panel-group" id="accordion">
    <?php foreach ($questions as $key => $question) { ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo $key; ?>">
                        <small class="text-info">
                            <strong>Question Id: (<?php echo $question['QuestionId'];?>)</strong>
                        </small>
                    </a>&nbsp;&nbsp;
                        <small class="text-info">
                            <?php echo substr(strip_tags($question['QuestionText']),0,40).'...'; ?>
                        </small>
                </h4>
            </div>
            <div id="collapse<?php echo $key; ?>" class="panel-collapse collapse">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <?php foreach ($prettyQuestions as $prettyQuestion) {
                                if ($prettyQuestion['QuestionId'] == $question['QuestionId']) { ?>
                                    <fieldset>
                                        <legend>Item</legend>
                                        <div class="mcat_question_text"><?php echo $prettyQuestion['QuestionText']; ?></div>
                                        <div class="mcat_label"><div class="mcat_solution_button" onclick="toggleSolution(this);">?</div><div class="mcat_answer_letter">A)</div><div class="mcat_answer_choice_container"><?php echo $prettyQuestion['AnswerText']; ?></div><div class="mcat_explanation_container" style="display:none"><?php echo $prettyQuestion['ExplanationText']; ?></div></div>
                                        <div class="mcat_label"><div class="mcat_solution_button" onclick="toggleSolution(this);">?</div><div class="mcat_answer_letter">B)</div><div class="mcat_answer_choice_container"><?php echo $prettyQuestion['Distractor1Text']; ?></div><div class="mcat_distractor_container" style="display:none"><?php echo $prettyQuestion['Pathology1Text']; ?></div></div>
                                        <div class="mcat_label"><div class="mcat_solution_button" onclick="toggleSolution(this);">?</div><div class="mcat_answer_letter">C)</div><div class="mcat_answer_choice_container"><?php echo $prettyQuestion['Distractor2Text']; ?></div><div class="mcat_distractor_container" style="display:none"><?php echo $prettyQuestion['Pathology2Text']; ?></div></div>
                                        <div class="mcat_label"><div class="mcat_solution_button" onclick="toggleSolution(this);">?</div><div class="mcat_answer_letter">D)</div><div class="mcat_answer_choice_container"><?php echo $prettyQuestion['Distractor3Text']; ?></div><div class="mcat_distractor_container" style="display:none"><?php echo $prettyQuestion['Pathology3Text']; ?></div></div>
                                    </fieldset>
                            <?php }}?>
                        </div>
                        <div class="col-sm-6">
                            <form action="/writer/update-discrete?page=<?php echo $page; ?>" method="post" enctype="multipart/form-data">
                                <div class="form-group">
                                    <input type="hidden" name="questionId" value="<?php echo $question['QuestionId']; ?>">
                                    <label for="questionText">Question Text:</label>
                                        <textarea class="form-control" id="questionText" name="questionText" rows="8"><?php echo htmlspecialchars($question['QuestionText']); ?></textarea>
                                        <input type="file" name="questionImage"><br/><hr/>
                                    <label for="answerText">Answer Text:</label>
                                        <textarea class="form-control" id="answerText" name="answerText" rows="8"><?php echo htmlspecialchars($question['AnswerText']); ?></textarea>
                                        <input type="file" name="answerImage"><br/><hr/>
                                    <label for="distractor1Text">Distractor 1 Text:</label>
                                        <textarea class="form-control" id="distractor1Text" name="distractor1Text" rows="8"><?php echo htmlspecialchars($question['Distractor1Text']); ?></textarea>
                                        <input type="file" name="distractor1Image"><br/><hr/>
                                    <label for="distractor2Text">Distractor 2 Text:</label>
                                        <textarea class="form-control" id="distractor2Text" name="distractor2Text" rows="8"><?php echo htmlspecialchars($question['Distractor2Text']); ?></textarea>
                                        <input type="file" name="distractor2Image"><br/><hr/>
                                    <label for="distractor3Text">Distractor 3 Text:</label>
                                        <textarea class="form-control" id="distractor3Text" name="distractor3Text" rows="8"><?php echo htmlspecialchars($question['Distractor3Text']); ?></textarea>
                                        <input type="file" name="distractor3Image"><br/><hr/>
                                    <label for="explanationText">Explanation Text:</label>
                                        <textarea class="form-control" id="explanationText" name="explanationText" rows="8"><?php echo htmlspecialchars($question['ExplanationText']); ?></textarea>
                                        <input type="file" name="explanationImage"><br/><hr/>
                                    <label for="pathology1Text">Pathology 1 Text:</label>
                                        <textarea class="form-control" id="pathology1Text" name="pathology1Text" rows="8"><?php echo htmlspecialchars($question['Pathology1Text']); ?></textarea>
                                        <input type="file" name="pathology1Image"><br/><hr/>
                                    <label for="pathology2Text">Pathology 2 Text:</label>
                                        <textarea class="form-control" id="pathology2Text" name="pathology2Text" rows="8"><?php echo htmlspecialchars($question['Pathology2Text']); ?></textarea>
                                        <input type="file" name="pathology2Image"><br/><hr/>
                                    <label for="pathology3Text">Pathology 3 Text:</label>
                                        <textarea class="form-control" id="pathology3Text" name="pathology3Text" rows="8"><?php echo htmlspecialchars($question['Pathology3Text']); ?></textarea>
                                        <input type="file" name="pathology3Image">
                                </div>
                                <button type="submit" class="btn btn-info">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
</div>