<script type="text/javascript">
    function toggleSolution(anchorTag) {
        var span = anchorTag.nextSibling.nextSibling.nextSibling;
        if (span.style.display == "none") {
            span.style.display = "inline";
        } else {
            span.style.display = "none";
        }
    }
</script>
<style>
    span.passage_equation {
        display: block;
        text-align: center;
        margin-bottom:20px;
        margin-top:20px;
    }
    span.question_equation {
        display:block;
        text-align:center;
        margin-top:5px;
        margin-bottom:5px;
    }	
	fieldset table {
		border-collapse: collapse; 
		border: solid thin;
		margin-left: auto;
		margin-right: auto;
		margin-top: 10px;
		margin-bottom: 10px;
	}
	fieldset thead {
		border: solid thin;
	}
	fieldset th {
		padding: 3px;
		border: solid thin;
	}
	fieldset td {
		padding: 3px;
	}
    .passage table {
        border-collapse: collapse;
        border: solid thin;
        margin-left: auto;
        margin-right: auto;
        margin-bottom:30px;
        margin-top:10px;
    }
    .passage td {
        padding:3px;
        border: solid thin;
    }
	.passage th {
		padding: 3px;
		text-align: center;
	}
    .mcat_answer_letter {
        float:left;
        padding-left:2px;
    }
    .mcat_solution_button {
        color:blue;
        margin-left:-13px;
        padding-left:1px;
        padding-right:1px;
        float:left;
        cursor:pointer;
        border:1px solid blue;
        border-radius:10px;
    }
    .mcat_answer_choice_container {
        margin-left:20px;
    }
    .mcat_distractor_container {
        color: red;
    }
    .mcat_explanation_container {
        color:blue;
    }
    .mcat_question_text img {
        display:block;
        margin-left:auto;
        margin-right:auto;
    }
    .mcat_label {
        padding:2px;
        margin-left:20px;
        min-height:30px;
    }
    .passage figure {
        text-align:center;
    }
    .passage figcaption {
        margin-top:20px;
        margin-bottom:20px;
    }
    fieldset {
        margin-bottom:20px;
    }
    legend {
        background-color:beige;
    }
    .mcat_question_text {
        margin-left:20px;
        margin-bottom:30px;
    }
</style>
<div class="text-danger"><?php echo $flash['message']; ?></div>
<nav>
    <ul class="pagination pagination-sm">
        <li class="previous <?php echo ($page == 1) ? 'disabled' : ''; ?>">
            <a href="/writer/manage-passages?page=<?php echo ($page == 1) ? 1 : $page-1; ?>"><span aria-hidden="true">&larr;</span> Prev</a>
        </li>
        <?php for ($i=1;$i<=$lastPage;$i++) {?>
            <li <?php if ($page == $i) {?>class="active"<?php } ?>><a href="/writer/manage-passages?page=<?php echo $i;?>"><?php echo $i; ?></a></li>
        <?php } ?>
        <li class="next <?php echo ($page == $lastPage) ? 'disabled' : ''; ?>">
            <a href="/writer/manage-passages?page=<?php echo ($page == $lastPage) ? $lastPage : $page+1; ?>">Next <span aria-hidden="true">&rarr;</span></a>
        </li>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="/writer/create-passage" class="btn btn-sm btn-success">New Passage</a>
    </ul>
</nav>
<div class="panel-group" id="accordion">
    <?php foreach ($passages as $passage) { ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo $passage['spelling'];?>">
                        <small class="text-info">
                            <strong><?php echo $passage['Description'].' ('.$passage['PassageId'].')';?></strong>
                        </small>
                    </a>&nbsp;&nbsp;
                    <small class="text-info">
                       Author: <?php echo ucfirst($passage['last_name']).', '.ucfirst($passage['first_name']); ?>
                    </small>
                </h4>
            </div>
            <div id="collapse<?php echo $passage['spelling'];?>" class="panel-collapse collapse">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="passage"><?php echo $passage['PrettyPassageText']; ?></div>
                                <?php foreach ($prettyQuestions as $question) {
                                    if ($question['PassageId'] == $passage['PassageId']) { ?>
                                        <fieldset>
                                            <legend>Item</legend>
                                            <div class="mcat_question_text"><?php echo $question['QuestionText']; ?></div>
                                            <div class="mcat_label"><div class="mcat_solution_button" onclick="toggleSolution(this);">?</div><div class="mcat_answer_letter">A)</div><div class="mcat_answer_choice_container"><?php echo $question['AnswerText']; ?></div><div class="mcat_explanation_container" style="display:none"><?php echo $question['ExplanationText']; ?></div></div>
                                            <div class="mcat_label"><div class="mcat_solution_button" onclick="toggleSolution(this);">?</div><div class="mcat_answer_letter">B)</div><div class="mcat_answer_choice_container"><?php echo $question['Distractor1Text']; ?></div><div class="mcat_distractor_container" style="display:none"><?php echo $question['Pathology1Text']; ?></div></div>
                                            <div class="mcat_label"><div class="mcat_solution_button" onclick="toggleSolution(this);">?</div><div class="mcat_answer_letter">C)</div><div class="mcat_answer_choice_container"><?php echo $question['Distractor2Text']; ?></div><div class="mcat_distractor_container" style="display:none"><?php echo $question['Pathology2Text']; ?></div></div>
                                            <div class="mcat_label"><div class="mcat_solution_button" onclick="toggleSolution(this);">?</div><div class="mcat_answer_letter">D)</div><div class="mcat_answer_choice_container"><?php echo $question['Distractor3Text']; ?></div><div class="mcat_distractor_container" style="display:none"><?php echo $question['Pathology3Text']; ?></div></div>
                                        </fieldset>
                                    <?php }
                                }
                            ?>
                        </div>
                        <div class="col-sm-6">
                            <form action="/writer/update-passage?page=<?php echo $page; ?>" method="post" enctype="multipart/form-data">
                                <div class="panel-group" id="secondAccordion">
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <h4 class="panel-title">
                                                <a data-toggle="collapse" data-parent="#secondAccordion" href="#collapsePassage<?php echo $passage['PassageId']; ?>">
                                                    <small class="text-info">
                                                        <strong>Passage</strong>
                                                    </small>
                                                </a>
                                            </h4>
                                        </div>
                                        <div id="collapsePassage<?php echo $passage['PassageId']; ?>" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <div class="form-group">
                                                    <label for="passageDescription">Passage Description:</label>
                                                        <input class="form-control" id="passageDescription" name="passageDescription" value="<?php echo htmlspecialchars($passage['Description']); ?>"><br/>
                                                    <label for="passageText">Passage Text</label>
                                                        <textarea class="form-control" id="passageText" name="passageText" rows="20"><?php echo htmlspecialchars($passage['PassageText']); ?></textarea><br/>
                                                    <label for="passageImage1">Passage Image 1:</label>
                                                        <input type="file" name="passageImage1"><br/>
                                                    <label for="passageImage2">Passage Image 2:</label>
                                                        <input type="file" name="passageImage2"><br/>
                                                    <label for="passageImage3">Passage Image 3:</label>
                                                        <input type="file" name="passageImage3"><br/>
                                                    <label for="passageImage4">Passage Image 4:</label>
                                                        <input type="file" name="passageImage4"><br/>
                                                    <label for="passageImage5">Passage Image 5:</label>
                                                        <input type="file" name="passageImage5"><br/>
                                                    <input type="hidden" name="passageId" value="<?php echo $passage['PassageId'];?>">
                                                        <input type="hidden" name="author" value="<?php echo $passage['Author'];?>">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <?php foreach ($questions as $key => $question) {
                                    if ($question['PassageId'] == $passage['PassageId']) { ?>
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <h4 class="panel-title">
                                                <a data-toggle="collapse" data-parent="#secondAccordion" href="#collapse<?php echo $key;?>">
                                                    <small class="text-info">
                                                        <strong>Question </strong>(Id = <?php echo $question['QuestionId']; ?>)
                                                    </small>
                                                </a>
                                            </h4>
                                        </div>
                                        <div id="collapse<?php echo $key; ?>" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <div class="form-group">
                                                    <input type="hidden" name="questions[<?php echo $key; ?>][questionId]" value="<?php echo $question['QuestionId']; ?>">
                                                    <label for="questionText">Question Text:</label>
                                                        <textarea class="form-control" id="questionText" name="questions[<?php echo $key; ?>][questionText]" rows=8""><?php echo htmlspecialchars($question['QuestionText']); ?></textarea>
                                                        <input type="file" name="<?php echo $key; ?>questionImage"><br/><hr/>
                                                    <label for="answerText">Answer Text:</label>
                                                        <textarea class="form-control" id="answerText" name="questions[<?php echo $key; ?>][answerText]" rows="8"><?php echo htmlspecialchars($question['AnswerText']); ?></textarea>
                                                        <input type="file" name="<?php echo $key; ?>answerImage"><br/><hr/>
                                                    <label for="distractor1Text">Distractor 1 Text:</label>
                                                        <textarea class="form-control" id="distractor1Text" name="questions[<?php echo $key; ?>][distractor1Text]" rows="8"><?php echo htmlspecialchars($question['Distractor1Text']); ?></textarea>
                                                        <input type="file" name="<?php echo $key; ?>distractor1Image"><br/><hr/>
                                                    <label for="distractor2Text">Distractor 2 Text:</label>
                                                        <textarea class="form-control" id="distractor2Text" name="questions[<?php echo $key; ?>][distractor2Text]" rows="8"><?php echo htmlspecialchars($question['Distractor2Text']); ?></textarea>
                                                        <input type="file" name="<?php echo $key; ?>distractor2Image"><br/><hr/>
                                                    <label for="distractor3Text">Distractor 3 Text:</label>
                                                        <textarea class="form-control" id="distractor3Text" name="questions[<?php echo $key; ?>][distractor3Text]" rows="8"><?php echo htmlspecialchars($question['Distractor3Text']); ?></textarea>
                                                        <input type="file" name="<?php echo $key; ?>distractor3Image"><br/><hr/>
                                                    <label for="explanationText">Explanation Text:</label>
                                                        <textarea class="form-control" id="explanationText" name="questions[<?php echo $key; ?>][explanationText]" rows="8"><?php echo htmlspecialchars($question['ExplanationText']); ?></textarea>
                                                        <input type="file" name="<?php echo $key; ?>explanationImage"><br/><hr/>
                                                    <label for="pathology1Text">Pathology 1 Text:</label>
                                                        <textarea class="form-control" id="pathology1Text" name="questions[<?php echo $key; ?>][pathology1Text]" rows="8"><?php echo htmlspecialchars($question['Pathology1Text']); ?></textarea>
                                                        <input type="file" name="<?php echo $key; ?>pathology1Image"><br/><hr/>
                                                    <label for="pathology2Text">Pathology 2 Text:</label>
                                                        <textarea class="form-control" id="pathology2Text" name="questions[<?php echo $key; ?>][pathology2Text]" rows="8"><?php echo htmlspecialchars($question['Pathology2Text']); ?></textarea>
                                                        <input type="file" name="<?php echo $key; ?>pathology2Image"><br/><hr/>
                                                    <label for="pathology3Text">Pathology 3 Text:</label>
                                                        <textarea class="form-control" id="pathology3Text" name="questions[<?php echo $key; ?>][pathology3Text]" rows="8"><?php echo htmlspecialchars($question['Pathology3Text']); ?></textarea>
                                                        <input type="file" name="<?php echo $key; ?>pathology3Image">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <?php }}?>
                                </div>
                                <button type="submit" class="btn btn-info">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
</div>